version: "3.7"
services:

  stakeholder-service:
    image: stakeholder-service:compose_build
    build:
      context: ./Stakeholders
      dockerfile: Dockerfile
    networks:
      - backend
    ports:
      - "8081:8081"
    env_file:
      - ./Stakeholders/.env
    depends_on:
      stakeholders-db:
        condition: service_healthy
    restart: on-failure

  stakeholders-db:
    image: neo4j:4.4
    container_name: stakeholders-db
    environment:
      NEO4J_AUTH: "neo4j/password"
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - stakeholders_db_data:/data
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "cypher-shell -u neo4j -p ${NEO4J_PASSWORD} -a neo4j://localhost:7687 'RETURN 1'"]
      interval: 10s
      timeout: 5s
      retries: 5

  blog-service:
    image: blog-service:compose_build
    build:
      context: ./Blog
      dockerfile: Dockerfile
    networks:
      - backend
    ports:
      - "8082:8082"
    env_file:
      - ./Blog/.env
    depends_on:
      - blog-db

  blog-db:
    image: mongo:latest
    container_name: blog-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO_INITDB_DATABASE: blog_db
    ports:
      - "27017:27017"
    volumes:
      - blog_db_data:/data/db
    networks:
      - backend
    
  api-gateway:
    build:
      context: .
      dockerfile: ./API_Gateway/Dockerfile
    ports:
      - "8000:8000"
    networks:
      - backend
    env_file:
      - ./API_Gateway/.env
    depends_on:
      - blog-service
      - stakeholder-service

networks:
  backend:
    driver: bridge

volumes:
  blog_db_data:
  stakeholders_db_data:
