// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: tour_service.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TourService_GetAllTours_FullMethodName           = "/tour.TourService/GetAllTours"
	TourService_GetTourByID_FullMethodName           = "/tour.TourService/GetTourByID"
	TourService_CreateTour_FullMethodName            = "/tour.TourService/CreateTour"
	TourService_UpdateTour_FullMethodName            = "/tour.TourService/UpdateTour"
	TourService_CreateKeyPoint_FullMethodName        = "/tour.TourService/CreateKeyPoint"
	TourService_UpdateKeyPoint_FullMethodName        = "/tour.TourService/UpdateKeyPoint"
	TourService_DeleteKeyPoint_FullMethodName        = "/tour.TourService/DeleteKeyPoint"
	TourService_StartTour_FullMethodName             = "/tour.TourService/StartTour"
	TourService_CheckProximity_FullMethodName        = "/tour.TourService/CheckProximity"
	TourService_AbandonTour_FullMethodName           = "/tour.TourService/AbandonTour"
	TourService_GetActiveTour_FullMethodName         = "/tour.TourService/GetActiveTour"
	TourService_CreateRecension_FullMethodName       = "/tour.TourService/CreateRecension"
	TourService_GetRecensionsByTourID_FullMethodName = "/tour.TourService/GetRecensionsByTourID"
)

// TourServiceClient is the client API for TourService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TourServiceClient interface {
	GetAllTours(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*TourListResponse, error)
	GetTourByID(ctx context.Context, in *TourIDRequest, opts ...grpc.CallOption) (*DetailedTourResponse, error)
	CreateTour(ctx context.Context, in *CreateTourRequest, opts ...grpc.CallOption) (*TourResponse, error)
	UpdateTour(ctx context.Context, in *UpdateTourRequest, opts ...grpc.CallOption) (*UpdateTourResponse, error)
	CreateKeyPoint(ctx context.Context, in *CreateKeyPointRequest, opts ...grpc.CallOption) (*CreateKeyPointResponse, error)
	UpdateKeyPoint(ctx context.Context, in *UpdateKeyPointRequest, opts ...grpc.CallOption) (*UpdateKeyPointResponse, error)
	DeleteKeyPoint(ctx context.Context, in *DeleteKeyPointRequest, opts ...grpc.CallOption) (*DeleteKeyPointResponse, error)
	StartTour(ctx context.Context, in *StartTourRequest, opts ...grpc.CallOption) (*TourExecutionResponse, error)
	CheckProximity(ctx context.Context, in *CheckProximityRequest, opts ...grpc.CallOption) (*TourExecutionResponse, error)
	AbandonTour(ctx context.Context, in *TourExecutionRequest, opts ...grpc.CallOption) (*TourExecutionResponse, error)
	GetActiveTour(ctx context.Context, in *GetActiveTourRequest, opts ...grpc.CallOption) (*TourExecutionResponse, error)
	CreateRecension(ctx context.Context, in *CreateRecensionRequest, opts ...grpc.CallOption) (*RecensionResponse, error)
	GetRecensionsByTourID(ctx context.Context, in *TourIDRequest, opts ...grpc.CallOption) (*RecensionListResponse, error)
}

type tourServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTourServiceClient(cc grpc.ClientConnInterface) TourServiceClient {
	return &tourServiceClient{cc}
}

func (c *tourServiceClient) GetAllTours(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*TourListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TourListResponse)
	err := c.cc.Invoke(ctx, TourService_GetAllTours_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tourServiceClient) GetTourByID(ctx context.Context, in *TourIDRequest, opts ...grpc.CallOption) (*DetailedTourResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DetailedTourResponse)
	err := c.cc.Invoke(ctx, TourService_GetTourByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tourServiceClient) CreateTour(ctx context.Context, in *CreateTourRequest, opts ...grpc.CallOption) (*TourResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TourResponse)
	err := c.cc.Invoke(ctx, TourService_CreateTour_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tourServiceClient) UpdateTour(ctx context.Context, in *UpdateTourRequest, opts ...grpc.CallOption) (*UpdateTourResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateTourResponse)
	err := c.cc.Invoke(ctx, TourService_UpdateTour_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tourServiceClient) CreateKeyPoint(ctx context.Context, in *CreateKeyPointRequest, opts ...grpc.CallOption) (*CreateKeyPointResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateKeyPointResponse)
	err := c.cc.Invoke(ctx, TourService_CreateKeyPoint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tourServiceClient) UpdateKeyPoint(ctx context.Context, in *UpdateKeyPointRequest, opts ...grpc.CallOption) (*UpdateKeyPointResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateKeyPointResponse)
	err := c.cc.Invoke(ctx, TourService_UpdateKeyPoint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tourServiceClient) DeleteKeyPoint(ctx context.Context, in *DeleteKeyPointRequest, opts ...grpc.CallOption) (*DeleteKeyPointResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteKeyPointResponse)
	err := c.cc.Invoke(ctx, TourService_DeleteKeyPoint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tourServiceClient) StartTour(ctx context.Context, in *StartTourRequest, opts ...grpc.CallOption) (*TourExecutionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TourExecutionResponse)
	err := c.cc.Invoke(ctx, TourService_StartTour_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tourServiceClient) CheckProximity(ctx context.Context, in *CheckProximityRequest, opts ...grpc.CallOption) (*TourExecutionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TourExecutionResponse)
	err := c.cc.Invoke(ctx, TourService_CheckProximity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tourServiceClient) AbandonTour(ctx context.Context, in *TourExecutionRequest, opts ...grpc.CallOption) (*TourExecutionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TourExecutionResponse)
	err := c.cc.Invoke(ctx, TourService_AbandonTour_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tourServiceClient) GetActiveTour(ctx context.Context, in *GetActiveTourRequest, opts ...grpc.CallOption) (*TourExecutionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TourExecutionResponse)
	err := c.cc.Invoke(ctx, TourService_GetActiveTour_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tourServiceClient) CreateRecension(ctx context.Context, in *CreateRecensionRequest, opts ...grpc.CallOption) (*RecensionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecensionResponse)
	err := c.cc.Invoke(ctx, TourService_CreateRecension_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tourServiceClient) GetRecensionsByTourID(ctx context.Context, in *TourIDRequest, opts ...grpc.CallOption) (*RecensionListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecensionListResponse)
	err := c.cc.Invoke(ctx, TourService_GetRecensionsByTourID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TourServiceServer is the server API for TourService service.
// All implementations must embed UnimplementedTourServiceServer
// for forward compatibility.
type TourServiceServer interface {
	GetAllTours(context.Context, *Empty) (*TourListResponse, error)
	GetTourByID(context.Context, *TourIDRequest) (*DetailedTourResponse, error)
	CreateTour(context.Context, *CreateTourRequest) (*TourResponse, error)
	UpdateTour(context.Context, *UpdateTourRequest) (*UpdateTourResponse, error)
	CreateKeyPoint(context.Context, *CreateKeyPointRequest) (*CreateKeyPointResponse, error)
	UpdateKeyPoint(context.Context, *UpdateKeyPointRequest) (*UpdateKeyPointResponse, error)
	DeleteKeyPoint(context.Context, *DeleteKeyPointRequest) (*DeleteKeyPointResponse, error)
	StartTour(context.Context, *StartTourRequest) (*TourExecutionResponse, error)
	CheckProximity(context.Context, *CheckProximityRequest) (*TourExecutionResponse, error)
	AbandonTour(context.Context, *TourExecutionRequest) (*TourExecutionResponse, error)
	GetActiveTour(context.Context, *GetActiveTourRequest) (*TourExecutionResponse, error)
	CreateRecension(context.Context, *CreateRecensionRequest) (*RecensionResponse, error)
	GetRecensionsByTourID(context.Context, *TourIDRequest) (*RecensionListResponse, error)
	mustEmbedUnimplementedTourServiceServer()
}

// UnimplementedTourServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTourServiceServer struct{}

func (UnimplementedTourServiceServer) GetAllTours(context.Context, *Empty) (*TourListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllTours not implemented")
}
func (UnimplementedTourServiceServer) GetTourByID(context.Context, *TourIDRequest) (*DetailedTourResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTourByID not implemented")
}
func (UnimplementedTourServiceServer) CreateTour(context.Context, *CreateTourRequest) (*TourResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTour not implemented")
}
func (UnimplementedTourServiceServer) UpdateTour(context.Context, *UpdateTourRequest) (*UpdateTourResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTour not implemented")
}
func (UnimplementedTourServiceServer) CreateKeyPoint(context.Context, *CreateKeyPointRequest) (*CreateKeyPointResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateKeyPoint not implemented")
}
func (UnimplementedTourServiceServer) UpdateKeyPoint(context.Context, *UpdateKeyPointRequest) (*UpdateKeyPointResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateKeyPoint not implemented")
}
func (UnimplementedTourServiceServer) DeleteKeyPoint(context.Context, *DeleteKeyPointRequest) (*DeleteKeyPointResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteKeyPoint not implemented")
}
func (UnimplementedTourServiceServer) StartTour(context.Context, *StartTourRequest) (*TourExecutionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartTour not implemented")
}
func (UnimplementedTourServiceServer) CheckProximity(context.Context, *CheckProximityRequest) (*TourExecutionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckProximity not implemented")
}
func (UnimplementedTourServiceServer) AbandonTour(context.Context, *TourExecutionRequest) (*TourExecutionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AbandonTour not implemented")
}
func (UnimplementedTourServiceServer) GetActiveTour(context.Context, *GetActiveTourRequest) (*TourExecutionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetActiveTour not implemented")
}
func (UnimplementedTourServiceServer) CreateRecension(context.Context, *CreateRecensionRequest) (*RecensionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateRecension not implemented")
}
func (UnimplementedTourServiceServer) GetRecensionsByTourID(context.Context, *TourIDRequest) (*RecensionListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRecensionsByTourID not implemented")
}
func (UnimplementedTourServiceServer) mustEmbedUnimplementedTourServiceServer() {}
func (UnimplementedTourServiceServer) testEmbeddedByValue()                     {}

// UnsafeTourServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TourServiceServer will
// result in compilation errors.
type UnsafeTourServiceServer interface {
	mustEmbedUnimplementedTourServiceServer()
}

func RegisterTourServiceServer(s grpc.ServiceRegistrar, srv TourServiceServer) {
	// If the following call pancis, it indicates UnimplementedTourServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TourService_ServiceDesc, srv)
}

func _TourService_GetAllTours_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TourServiceServer).GetAllTours(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TourService_GetAllTours_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TourServiceServer).GetAllTours(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _TourService_GetTourByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TourIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TourServiceServer).GetTourByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TourService_GetTourByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TourServiceServer).GetTourByID(ctx, req.(*TourIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TourService_CreateTour_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTourRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TourServiceServer).CreateTour(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TourService_CreateTour_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TourServiceServer).CreateTour(ctx, req.(*CreateTourRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TourService_UpdateTour_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTourRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TourServiceServer).UpdateTour(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TourService_UpdateTour_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TourServiceServer).UpdateTour(ctx, req.(*UpdateTourRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TourService_CreateKeyPoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateKeyPointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TourServiceServer).CreateKeyPoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TourService_CreateKeyPoint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TourServiceServer).CreateKeyPoint(ctx, req.(*CreateKeyPointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TourService_UpdateKeyPoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateKeyPointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TourServiceServer).UpdateKeyPoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TourService_UpdateKeyPoint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TourServiceServer).UpdateKeyPoint(ctx, req.(*UpdateKeyPointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TourService_DeleteKeyPoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteKeyPointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TourServiceServer).DeleteKeyPoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TourService_DeleteKeyPoint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TourServiceServer).DeleteKeyPoint(ctx, req.(*DeleteKeyPointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TourService_StartTour_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartTourRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TourServiceServer).StartTour(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TourService_StartTour_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TourServiceServer).StartTour(ctx, req.(*StartTourRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TourService_CheckProximity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckProximityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TourServiceServer).CheckProximity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TourService_CheckProximity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TourServiceServer).CheckProximity(ctx, req.(*CheckProximityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TourService_AbandonTour_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TourExecutionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TourServiceServer).AbandonTour(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TourService_AbandonTour_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TourServiceServer).AbandonTour(ctx, req.(*TourExecutionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TourService_GetActiveTour_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetActiveTourRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TourServiceServer).GetActiveTour(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TourService_GetActiveTour_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TourServiceServer).GetActiveTour(ctx, req.(*GetActiveTourRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TourService_CreateRecension_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRecensionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TourServiceServer).CreateRecension(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TourService_CreateRecension_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TourServiceServer).CreateRecension(ctx, req.(*CreateRecensionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TourService_GetRecensionsByTourID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TourIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TourServiceServer).GetRecensionsByTourID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TourService_GetRecensionsByTourID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TourServiceServer).GetRecensionsByTourID(ctx, req.(*TourIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TourService_ServiceDesc is the grpc.ServiceDesc for TourService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TourService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tour.TourService",
	HandlerType: (*TourServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAllTours",
			Handler:    _TourService_GetAllTours_Handler,
		},
		{
			MethodName: "GetTourByID",
			Handler:    _TourService_GetTourByID_Handler,
		},
		{
			MethodName: "CreateTour",
			Handler:    _TourService_CreateTour_Handler,
		},
		{
			MethodName: "UpdateTour",
			Handler:    _TourService_UpdateTour_Handler,
		},
		{
			MethodName: "CreateKeyPoint",
			Handler:    _TourService_CreateKeyPoint_Handler,
		},
		{
			MethodName: "UpdateKeyPoint",
			Handler:    _TourService_UpdateKeyPoint_Handler,
		},
		{
			MethodName: "DeleteKeyPoint",
			Handler:    _TourService_DeleteKeyPoint_Handler,
		},
		{
			MethodName: "StartTour",
			Handler:    _TourService_StartTour_Handler,
		},
		{
			MethodName: "CheckProximity",
			Handler:    _TourService_CheckProximity_Handler,
		},
		{
			MethodName: "AbandonTour",
			Handler:    _TourService_AbandonTour_Handler,
		},
		{
			MethodName: "GetActiveTour",
			Handler:    _TourService_GetActiveTour_Handler,
		},
		{
			MethodName: "CreateRecension",
			Handler:    _TourService_CreateRecension_Handler,
		},
		{
			MethodName: "GetRecensionsByTourID",
			Handler:    _TourService_GetRecensionsByTourID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tour_service.proto",
}
