// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.31.1
// source: Tours/proto/tour_service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TourDifficulty int32

const (
	TourDifficulty_EASY   TourDifficulty = 0
	TourDifficulty_MEDIUM TourDifficulty = 1
	TourDifficulty_HARD   TourDifficulty = 2
)

// Enum value maps for TourDifficulty.
var (
	TourDifficulty_name = map[int32]string{
		0: "EASY",
		1: "MEDIUM",
		2: "HARD",
	}
	TourDifficulty_value = map[string]int32{
		"EASY":   0,
		"MEDIUM": 1,
		"HARD":   2,
	}
)

func (x TourDifficulty) Enum() *TourDifficulty {
	p := new(TourDifficulty)
	*p = x
	return p
}

func (x TourDifficulty) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TourDifficulty) Descriptor() protoreflect.EnumDescriptor {
	return file_Tours_proto_tour_service_proto_enumTypes[0].Descriptor()
}

func (TourDifficulty) Type() protoreflect.EnumType {
	return &file_Tours_proto_tour_service_proto_enumTypes[0]
}

func (x TourDifficulty) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TourDifficulty.Descriptor instead.
func (TourDifficulty) EnumDescriptor() ([]byte, []int) {
	return file_Tours_proto_tour_service_proto_rawDescGZIP(), []int{0}
}

type TourTag int32

const (
	TourTag_Nature     TourTag = 0
	TourTag_Historical TourTag = 1
	TourTag_Adventure  TourTag = 2
	TourTag_Cultural   TourTag = 3
	TourTag_Wildlife   TourTag = 4
	TourTag_Relaxation TourTag = 5
	TourTag_Beach      TourTag = 6
	TourTag_Mountain   TourTag = 7
	TourTag_Urban      TourTag = 8
)

// Enum value maps for TourTag.
var (
	TourTag_name = map[int32]string{
		0: "Nature",
		1: "Historical",
		2: "Adventure",
		3: "Cultural",
		4: "Wildlife",
		5: "Relaxation",
		6: "Beach",
		7: "Mountain",
		8: "Urban",
	}
	TourTag_value = map[string]int32{
		"Nature":     0,
		"Historical": 1,
		"Adventure":  2,
		"Cultural":   3,
		"Wildlife":   4,
		"Relaxation": 5,
		"Beach":      6,
		"Mountain":   7,
		"Urban":      8,
	}
)

func (x TourTag) Enum() *TourTag {
	p := new(TourTag)
	*p = x
	return p
}

func (x TourTag) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TourTag) Descriptor() protoreflect.EnumDescriptor {
	return file_Tours_proto_tour_service_proto_enumTypes[1].Descriptor()
}

func (TourTag) Type() protoreflect.EnumType {
	return &file_Tours_proto_tour_service_proto_enumTypes[1]
}

func (x TourTag) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TourTag.Descriptor instead.
func (TourTag) EnumDescriptor() ([]byte, []int) {
	return file_Tours_proto_tour_service_proto_rawDescGZIP(), []int{1}
}

type TourStatus int32

const (
	TourStatus_DRAFT     TourStatus = 0
	TourStatus_PUBLISHED TourStatus = 1
	TourStatus_ARCHIVED  TourStatus = 2
)

// Enum value maps for TourStatus.
var (
	TourStatus_name = map[int32]string{
		0: "DRAFT",
		1: "PUBLISHED",
		2: "ARCHIVED",
	}
	TourStatus_value = map[string]int32{
		"DRAFT":     0,
		"PUBLISHED": 1,
		"ARCHIVED":  2,
	}
)

func (x TourStatus) Enum() *TourStatus {
	p := new(TourStatus)
	*p = x
	return p
}

func (x TourStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TourStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_Tours_proto_tour_service_proto_enumTypes[2].Descriptor()
}

func (TourStatus) Type() protoreflect.EnumType {
	return &file_Tours_proto_tour_service_proto_enumTypes[2]
}

func (x TourStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TourStatus.Descriptor instead.
func (TourStatus) EnumDescriptor() ([]byte, []int) {
	return file_Tours_proto_tour_service_proto_rawDescGZIP(), []int{2}
}

type Tour struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AuthorId      string                 `protobuf:"bytes,2,opt,name=authorId,proto3" json:"authorId,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Difficulty    TourDifficulty         `protobuf:"varint,5,opt,name=difficulty,proto3,enum=tour.TourDifficulty" json:"difficulty,omitempty"`
	Tags          []TourTag              `protobuf:"varint,6,rep,packed,name=tags,proto3,enum=tour.TourTag" json:"tags,omitempty"`
	Status        TourStatus             `protobuf:"varint,7,opt,name=status,proto3,enum=tour.TourStatus" json:"status,omitempty"`
	Price         float32                `protobuf:"fixed32,8,opt,name=price,proto3" json:"price,omitempty"`
	TravelTimes   map[string]float32     `protobuf:"bytes,9,rep,name=travelTimes,proto3" json:"travelTimes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed32,2,opt,name=value"`
	Length        float32                `protobuf:"fixed32,10,opt,name=length,proto3" json:"length,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tour) Reset() {
	*x = Tour{}
	mi := &file_Tours_proto_tour_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tour) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tour) ProtoMessage() {}

func (x *Tour) ProtoReflect() protoreflect.Message {
	mi := &file_Tours_proto_tour_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tour.ProtoReflect.Descriptor instead.
func (*Tour) Descriptor() ([]byte, []int) {
	return file_Tours_proto_tour_service_proto_rawDescGZIP(), []int{0}
}

func (x *Tour) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Tour) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

func (x *Tour) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Tour) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Tour) GetDifficulty() TourDifficulty {
	if x != nil {
		return x.Difficulty
	}
	return TourDifficulty_EASY
}

func (x *Tour) GetTags() []TourTag {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Tour) GetStatus() TourStatus {
	if x != nil {
		return x.Status
	}
	return TourStatus_DRAFT
}

func (x *Tour) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Tour) GetTravelTimes() map[string]float32 {
	if x != nil {
		return x.TravelTimes
	}
	return nil
}

func (x *Tour) GetLength() float32 {
	if x != nil {
		return x.Length
	}
	return 0
}

type KeyPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TourId        string                 `protobuf:"bytes,2,opt,name=tourId,proto3" json:"tourId,omitempty"`
	Longitude     float32                `protobuf:"fixed32,3,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Latitude      float32                `protobuf:"fixed32,4,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Name          string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,7,opt,name=imageUrl,proto3" json:"imageUrl,omitempty"`
	Order         int64                  `protobuf:"varint,8,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyPoint) Reset() {
	*x = KeyPoint{}
	mi := &file_Tours_proto_tour_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyPoint) ProtoMessage() {}

func (x *KeyPoint) ProtoReflect() protoreflect.Message {
	mi := &file_Tours_proto_tour_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyPoint.ProtoReflect.Descriptor instead.
func (*KeyPoint) Descriptor() ([]byte, []int) {
	return file_Tours_proto_tour_service_proto_rawDescGZIP(), []int{1}
}

func (x *KeyPoint) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *KeyPoint) GetTourId() string {
	if x != nil {
		return x.TourId
	}
	return ""
}

func (x *KeyPoint) GetLongitude() float32 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *KeyPoint) GetLatitude() float32 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *KeyPoint) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *KeyPoint) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *KeyPoint) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *KeyPoint) GetOrder() int64 {
	if x != nil {
		return x.Order
	}
	return 0
}

type TouristPosition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Latitude      float64                `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TouristPosition) Reset() {
	*x = TouristPosition{}
	mi := &file_Tours_proto_tour_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TouristPosition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TouristPosition) ProtoMessage() {}

func (x *TouristPosition) ProtoReflect() protoreflect.Message {
	mi := &file_Tours_proto_tour_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TouristPosition.ProtoReflect.Descriptor instead.
func (*TouristPosition) Descriptor() ([]byte, []int) {
	return file_Tours_proto_tour_service_proto_rawDescGZIP(), []int{2}
}

func (x *TouristPosition) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *TouristPosition) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

type CompletedKeyPoint struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	KeyPointId     string                 `protobuf:"bytes,1,opt,name=keyPointId,proto3" json:"keyPointId,omitempty"`
	CompletionTime string                 `protobuf:"bytes,2,opt,name=completionTime,proto3" json:"completionTime,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CompletedKeyPoint) Reset() {
	*x = CompletedKeyPoint{}
	mi := &file_Tours_proto_tour_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompletedKeyPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompletedKeyPoint) ProtoMessage() {}

func (x *CompletedKeyPoint) ProtoReflect() protoreflect.Message {
	mi := &file_Tours_proto_tour_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompletedKeyPoint.ProtoReflect.Descriptor instead.
func (*CompletedKeyPoint) Descriptor() ([]byte, []int) {
	return file_Tours_proto_tour_service_proto_rawDescGZIP(), []int{3}
}

func (x *CompletedKeyPoint) GetKeyPointId() string {
	if x != nil {
		return x.KeyPointId
	}
	return ""
}

func (x *CompletedKeyPoint) GetCompletionTime() string {
	if x != nil {
		return x.CompletionTime
	}
	return ""
}

type TourExecutionResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TourId             string                 `protobuf:"bytes,2,opt,name=tourId,proto3" json:"tourId,omitempty"`
	TouristId          string                 `protobuf:"bytes,3,opt,name=touristId,proto3" json:"touristId,omitempty"`
	Status             string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	StartTime          string                 `protobuf:"bytes,5,opt,name=startTime,proto3" json:"startTime,omitempty"`
	LastActivity       string                 `protobuf:"bytes,6,opt,name=lastActivity,proto3" json:"lastActivity,omitempty"`
	CompletionTime     string                 `protobuf:"bytes,7,opt,name=completionTime,proto3" json:"completionTime,omitempty"`
	CompletedKeyPoints []*CompletedKeyPoint   `protobuf:"bytes,8,rep,name=completedKeyPoints,proto3" json:"completedKeyPoints,omitempty"`
	CurrentPosition    *TouristPosition       `protobuf:"bytes,9,opt,name=currentPosition,proto3" json:"currentPosition,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *TourExecutionResponse) Reset() {
	*x = TourExecutionResponse{}
	mi := &file_Tours_proto_tour_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TourExecutionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TourExecutionResponse) ProtoMessage() {}

func (x *TourExecutionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Tours_proto_tour_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TourExecutionResponse.ProtoReflect.Descriptor instead.
func (*TourExecutionResponse) Descriptor() ([]byte, []int) {
	return file_Tours_proto_tour_service_proto_rawDescGZIP(), []int{4}
}

func (x *TourExecutionResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TourExecutionResponse) GetTourId() string {
	if x != nil {
		return x.TourId
	}
	return ""
}

func (x *TourExecutionResponse) GetTouristId() string {
	if x != nil {
		return x.TouristId
	}
	return ""
}

func (x *TourExecutionResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TourExecutionResponse) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *TourExecutionResponse) GetLastActivity() string {
	if x != nil {
		return x.LastActivity
	}
	return ""
}

func (x *TourExecutionResponse) GetCompletionTime() string {
	if x != nil {
		return x.CompletionTime
	}
	return ""
}

func (x *TourExecutionResponse) GetCompletedKeyPoints() []*CompletedKeyPoint {
	if x != nil {
		return x.CompletedKeyPoints
	}
	return nil
}

func (x *TourExecutionResponse) GetCurrentPosition() *TouristPosition {
	if x != nil {
		return x.CurrentPosition
	}
	return nil
}

type StartTourRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TourId        string                 `protobuf:"bytes,1,opt,name=tourId,proto3" json:"tourId,omitempty"`
	Position      *TouristPosition       `protobuf:"bytes,2,opt,name=position,proto3" json:"position,omitempty"`
	TouristId     string                 `protobuf:"bytes,3,opt,name=touristId,proto3" json:"touristId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartTourRequest) Reset() {
	*x = StartTourRequest{}
	mi := &file_Tours_proto_tour_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartTourRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartTourRequest) ProtoMessage() {}

func (x *StartTourRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Tours_proto_tour_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartTourRequest.ProtoReflect.Descriptor instead.
func (*StartTourRequest) Descriptor() ([]byte, []int) {
	return file_Tours_proto_tour_service_proto_rawDescGZIP(), []int{5}
}

func (x *StartTourRequest) GetTourId() string {
	if x != nil {
		return x.TourId
	}
	return ""
}

func (x *StartTourRequest) GetPosition() *TouristPosition {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *StartTourRequest) GetTouristId() string {
	if x != nil {
		return x.TouristId
	}
	return ""
}

type TourExecutionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TouristId     string                 `protobuf:"bytes,2,opt,name=touristId,proto3" json:"touristId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TourExecutionRequest) Reset() {
	*x = TourExecutionRequest{}
	mi := &file_Tours_proto_tour_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TourExecutionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TourExecutionRequest) ProtoMessage() {}

func (x *TourExecutionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Tours_proto_tour_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TourExecutionRequest.ProtoReflect.Descriptor instead.
func (*TourExecutionRequest) Descriptor() ([]byte, []int) {
	return file_Tours_proto_tour_service_proto_rawDescGZIP(), []int{6}
}

func (x *TourExecutionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TourExecutionRequest) GetTouristId() string {
	if x != nil {
		return x.TouristId
	}
	return ""
}

type ArchiveTourRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TourId        string                 `protobuf:"bytes,1,opt,name=tourId,proto3" json:"tourId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArchiveTourRequest) Reset() {
	*x = ArchiveTourRequest{}
	mi := &file_Tours_proto_tour_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArchiveTourRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArchiveTourRequest) ProtoMessage() {}

func (x *ArchiveTourRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Tours_proto_tour_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArchiveTourRequest.ProtoReflect.Descriptor instead.
func (*ArchiveTourRequest) Descriptor() ([]byte, []int) {
	return file_Tours_proto_tour_service_proto_rawDescGZIP(), []int{7}
}

func (x *ArchiveTourRequest) GetTourId() string {
	if x != nil {
		return x.TourId
	}
	return ""
}

type ArchiveTourResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArchiveTourResponse) Reset() {
	*x = ArchiveTourResponse{}
	mi := &file_Tours_proto_tour_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArchiveTourResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArchiveTourResponse) ProtoMessage() {}

func (x *ArchiveTourResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Tours_proto_tour_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArchiveTourResponse.ProtoReflect.Descriptor instead.
func (*ArchiveTourResponse) Descriptor() ([]byte, []int) {
	return file_Tours_proto_tour_service_proto_rawDescGZIP(), []int{8}
}

func (x *ArchiveTourResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PublishTourRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TourId        string                 `protobuf:"bytes,1,opt,name=tourId,proto3" json:"tourId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishTourRequest) Reset() {
	*x = PublishTourRequest{}
	mi := &file_Tours_proto_tour_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishTourRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishTourRequest) ProtoMessage() {}

func (x *PublishTourRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Tours_proto_tour_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishTourRequest.ProtoReflect.Descriptor instead.
func (*PublishTourRequest) Descriptor() ([]byte, []int) {
	return file_Tours_proto_tour_service_proto_rawDescGZIP(), []int{9}
}

func (x *PublishTourRequest) GetTourId() string {
	if x != nil {
		return x.TourId
	}
	return ""
}

type PublishTourResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishTourResponse) Reset() {
	*x = PublishTourResponse{}
	mi := &file_Tours_proto_tour_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishTourResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishTourResponse) ProtoMessage() {}

func (x *PublishTourResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Tours_proto_tour_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishTourResponse.ProtoReflect.Descriptor instead.
func (*PublishTourResponse) Descriptor() ([]byte, []int) {
	return file_Tours_proto_tour_service_proto_rawDescGZIP(), []int{10}
}

func (x *PublishTourResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_Tours_proto_tour_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_Tours_proto_tour_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_Tours_proto_tour_service_proto_rawDescGZIP(), []int{11}
}

type Recension struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AuthorId      string                 `protobuf:"bytes,2,opt,name=authorId,proto3" json:"authorId,omitempty"`
	TourId        string                 `protobuf:"bytes,3,opt,name=tourId,proto3" json:"tourId,omitempty"`
	Rating        int32                  `protobuf:"varint,4,opt,name=rating,proto3" json:"rating,omitempty"`
	VisitDate     string                 `protobuf:"bytes,5,opt,name=visitDate,proto3" json:"visitDate,omitempty"`
	Comment       string                 `protobuf:"bytes,6,opt,name=comment,proto3" json:"comment,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,7,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	Pictures      []string               `protobuf:"bytes,8,rep,name=pictures,proto3" json:"pictures,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Recension) Reset() {
	*x = Recension{}
	mi := &file_Tours_proto_tour_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Recension) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Recension) ProtoMessage() {}

func (x *Recension) ProtoReflect() protoreflect.Message {
	mi := &file_Tours_proto_tour_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Recension.ProtoReflect.Descriptor instead.
func (*Recension) Descriptor() ([]byte, []int) {
	return file_Tours_proto_tour_service_proto_rawDescGZIP(), []int{12}
}

func (x *Recension) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Recension) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

func (x *Recension) GetTourId() string {
	if x != nil {
		return x.TourId
	}
	return ""
}

func (x *Recension) GetRating() int32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *Recension) GetVisitDate() string {
	if x != nil {
		return x.VisitDate
	}
	return ""
}

func (x *Recension) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *Recension) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Recension) GetPictures() []string {
	if x != nil {
		return x.Pictures
	}
	return nil
}

type TourListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tours         []*Tour                `protobuf:"bytes,1,rep,name=tours,proto3" json:"tours,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TourListResponse) Reset() {
	*x = TourListResponse{}
	mi := &file_Tours_proto_tour_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TourListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TourListResponse) ProtoMessage() {}

func (x *TourListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Tours_proto_tour_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TourListResponse.ProtoReflect.Descriptor instead.
func (*TourListResponse) Descriptor() ([]byte, []int) {
	return file_Tours_proto_tour_service_proto_rawDescGZIP(), []int{13}
}

func (x *TourListResponse) GetTours() []*Tour {
	if x != nil {
		return x.Tours
	}
	return nil
}

type TourIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TourIDRequest) Reset() {
	*x = TourIDRequest{}
	mi := &file_Tours_proto_tour_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TourIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TourIDRequest) ProtoMessage() {}

func (x *TourIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Tours_proto_tour_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TourIDRequest.ProtoReflect.Descriptor instead.
func (*TourIDRequest) Descriptor() ([]byte, []int) {
	return file_Tours_proto_tour_service_proto_rawDescGZIP(), []int{14}
}

func (x *TourIDRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DetailedTourResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tour          *Tour                  `protobuf:"bytes,1,opt,name=tour,proto3" json:"tour,omitempty"`
	KeyPoints     []*KeyPoint            `protobuf:"bytes,2,rep,name=keyPoints,proto3" json:"keyPoints,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetailedTourResponse) Reset() {
	*x = DetailedTourResponse{}
	mi := &file_Tours_proto_tour_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetailedTourResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetailedTourResponse) ProtoMessage() {}

func (x *DetailedTourResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Tours_proto_tour_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetailedTourResponse.ProtoReflect.Descriptor instead.
func (*DetailedTourResponse) Descriptor() ([]byte, []int) {
	return file_Tours_proto_tour_service_proto_rawDescGZIP(), []int{15}
}

func (x *DetailedTourResponse) GetTour() *Tour {
	if x != nil {
		return x.Tour
	}
	return nil
}

func (x *DetailedTourResponse) GetKeyPoints() []*KeyPoint {
	if x != nil {
		return x.KeyPoints
	}
	return nil
}

type TourResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tour          *Tour                  `protobuf:"bytes,1,opt,name=tour,proto3" json:"tour,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TourResponse) Reset() {
	*x = TourResponse{}
	mi := &file_Tours_proto_tour_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TourResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TourResponse) ProtoMessage() {}

func (x *TourResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Tours_proto_tour_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TourResponse.ProtoReflect.Descriptor instead.
func (*TourResponse) Descriptor() ([]byte, []int) {
	return file_Tours_proto_tour_service_proto_rawDescGZIP(), []int{16}
}

func (x *TourResponse) GetTour() *Tour {
	if x != nil {
		return x.Tour
	}
	return nil
}

type CreateTourRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tour          *Tour                  `protobuf:"bytes,1,opt,name=tour,proto3" json:"tour,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTourRequest) Reset() {
	*x = CreateTourRequest{}
	mi := &file_Tours_proto_tour_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTourRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTourRequest) ProtoMessage() {}

func (x *CreateTourRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Tours_proto_tour_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTourRequest.ProtoReflect.Descriptor instead.
func (*CreateTourRequest) Descriptor() ([]byte, []int) {
	return file_Tours_proto_tour_service_proto_rawDescGZIP(), []int{17}
}

func (x *CreateTourRequest) GetTour() *Tour {
	if x != nil {
		return x.Tour
	}
	return nil
}

type UpdateTourRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tour          *Tour                  `protobuf:"bytes,1,opt,name=tour,proto3" json:"tour,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTourRequest) Reset() {
	*x = UpdateTourRequest{}
	mi := &file_Tours_proto_tour_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTourRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTourRequest) ProtoMessage() {}

func (x *UpdateTourRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Tours_proto_tour_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTourRequest.ProtoReflect.Descriptor instead.
func (*UpdateTourRequest) Descriptor() ([]byte, []int) {
	return file_Tours_proto_tour_service_proto_rawDescGZIP(), []int{18}
}

func (x *UpdateTourRequest) GetTour() *Tour {
	if x != nil {
		return x.Tour
	}
	return nil
}

type UpdateTourResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tour          *Tour                  `protobuf:"bytes,1,opt,name=tour,proto3" json:"tour,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTourResponse) Reset() {
	*x = UpdateTourResponse{}
	mi := &file_Tours_proto_tour_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTourResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTourResponse) ProtoMessage() {}

func (x *UpdateTourResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Tours_proto_tour_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTourResponse.ProtoReflect.Descriptor instead.
func (*UpdateTourResponse) Descriptor() ([]byte, []int) {
	return file_Tours_proto_tour_service_proto_rawDescGZIP(), []int{19}
}

func (x *UpdateTourResponse) GetTour() *Tour {
	if x != nil {
		return x.Tour
	}
	return nil
}

type CreateKeyPointRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyPoint      *KeyPoint              `protobuf:"bytes,1,opt,name=keyPoint,proto3" json:"keyPoint,omitempty"`
	ImageBase64   string                 `protobuf:"bytes,2,opt,name=imageBase64,proto3" json:"imageBase64,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateKeyPointRequest) Reset() {
	*x = CreateKeyPointRequest{}
	mi := &file_Tours_proto_tour_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateKeyPointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateKeyPointRequest) ProtoMessage() {}

func (x *CreateKeyPointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Tours_proto_tour_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateKeyPointRequest.ProtoReflect.Descriptor instead.
func (*CreateKeyPointRequest) Descriptor() ([]byte, []int) {
	return file_Tours_proto_tour_service_proto_rawDescGZIP(), []int{20}
}

func (x *CreateKeyPointRequest) GetKeyPoint() *KeyPoint {
	if x != nil {
		return x.KeyPoint
	}
	return nil
}

func (x *CreateKeyPointRequest) GetImageBase64() string {
	if x != nil {
		return x.ImageBase64
	}
	return ""
}

type CreateKeyPointResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyPoint      *KeyPoint              `protobuf:"bytes,1,opt,name=keyPoint,proto3" json:"keyPoint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateKeyPointResponse) Reset() {
	*x = CreateKeyPointResponse{}
	mi := &file_Tours_proto_tour_service_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateKeyPointResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateKeyPointResponse) ProtoMessage() {}

func (x *CreateKeyPointResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Tours_proto_tour_service_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateKeyPointResponse.ProtoReflect.Descriptor instead.
func (*CreateKeyPointResponse) Descriptor() ([]byte, []int) {
	return file_Tours_proto_tour_service_proto_rawDescGZIP(), []int{21}
}

func (x *CreateKeyPointResponse) GetKeyPoint() *KeyPoint {
	if x != nil {
		return x.KeyPoint
	}
	return nil
}

type UpdateKeyPointRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyPoint      *KeyPoint              `protobuf:"bytes,1,opt,name=keyPoint,proto3" json:"keyPoint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateKeyPointRequest) Reset() {
	*x = UpdateKeyPointRequest{}
	mi := &file_Tours_proto_tour_service_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateKeyPointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateKeyPointRequest) ProtoMessage() {}

func (x *UpdateKeyPointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Tours_proto_tour_service_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateKeyPointRequest.ProtoReflect.Descriptor instead.
func (*UpdateKeyPointRequest) Descriptor() ([]byte, []int) {
	return file_Tours_proto_tour_service_proto_rawDescGZIP(), []int{22}
}

func (x *UpdateKeyPointRequest) GetKeyPoint() *KeyPoint {
	if x != nil {
		return x.KeyPoint
	}
	return nil
}

type UpdateKeyPointResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyPoint      *KeyPoint              `protobuf:"bytes,1,opt,name=keyPoint,proto3" json:"keyPoint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateKeyPointResponse) Reset() {
	*x = UpdateKeyPointResponse{}
	mi := &file_Tours_proto_tour_service_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateKeyPointResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateKeyPointResponse) ProtoMessage() {}

func (x *UpdateKeyPointResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Tours_proto_tour_service_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateKeyPointResponse.ProtoReflect.Descriptor instead.
func (*UpdateKeyPointResponse) Descriptor() ([]byte, []int) {
	return file_Tours_proto_tour_service_proto_rawDescGZIP(), []int{23}
}

func (x *UpdateKeyPointResponse) GetKeyPoint() *KeyPoint {
	if x != nil {
		return x.KeyPoint
	}
	return nil
}

type DeleteKeyPointRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyPointId    string                 `protobuf:"bytes,1,opt,name=keyPointId,proto3" json:"keyPointId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteKeyPointRequest) Reset() {
	*x = DeleteKeyPointRequest{}
	mi := &file_Tours_proto_tour_service_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteKeyPointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteKeyPointRequest) ProtoMessage() {}

func (x *DeleteKeyPointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Tours_proto_tour_service_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteKeyPointRequest.ProtoReflect.Descriptor instead.
func (*DeleteKeyPointRequest) Descriptor() ([]byte, []int) {
	return file_Tours_proto_tour_service_proto_rawDescGZIP(), []int{24}
}

func (x *DeleteKeyPointRequest) GetKeyPointId() string {
	if x != nil {
		return x.KeyPointId
	}
	return ""
}

type DeleteKeyPointResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteKeyPointResponse) Reset() {
	*x = DeleteKeyPointResponse{}
	mi := &file_Tours_proto_tour_service_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteKeyPointResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteKeyPointResponse) ProtoMessage() {}

func (x *DeleteKeyPointResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Tours_proto_tour_service_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteKeyPointResponse.ProtoReflect.Descriptor instead.
func (*DeleteKeyPointResponse) Descriptor() ([]byte, []int) {
	return file_Tours_proto_tour_service_proto_rawDescGZIP(), []int{25}
}

func (x *DeleteKeyPointResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CheckProximityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Position      *TouristPosition       `protobuf:"bytes,2,opt,name=position,proto3" json:"position,omitempty"`
	TouristId     string                 `protobuf:"bytes,3,opt,name=touristId,proto3" json:"touristId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckProximityRequest) Reset() {
	*x = CheckProximityRequest{}
	mi := &file_Tours_proto_tour_service_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckProximityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckProximityRequest) ProtoMessage() {}

func (x *CheckProximityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Tours_proto_tour_service_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckProximityRequest.ProtoReflect.Descriptor instead.
func (*CheckProximityRequest) Descriptor() ([]byte, []int) {
	return file_Tours_proto_tour_service_proto_rawDescGZIP(), []int{26}
}

func (x *CheckProximityRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CheckProximityRequest) GetPosition() *TouristPosition {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *CheckProximityRequest) GetTouristId() string {
	if x != nil {
		return x.TouristId
	}
	return ""
}

type GetActiveTourRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TouristId     string                 `protobuf:"bytes,1,opt,name=touristId,proto3" json:"touristId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActiveTourRequest) Reset() {
	*x = GetActiveTourRequest{}
	mi := &file_Tours_proto_tour_service_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActiveTourRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActiveTourRequest) ProtoMessage() {}

func (x *GetActiveTourRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Tours_proto_tour_service_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActiveTourRequest.ProtoReflect.Descriptor instead.
func (*GetActiveTourRequest) Descriptor() ([]byte, []int) {
	return file_Tours_proto_tour_service_proto_rawDescGZIP(), []int{27}
}

func (x *GetActiveTourRequest) GetTouristId() string {
	if x != nil {
		return x.TouristId
	}
	return ""
}

type CreateRecensionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Recension     *Recension             `protobuf:"bytes,1,opt,name=recension,proto3" json:"recension,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRecensionRequest) Reset() {
	*x = CreateRecensionRequest{}
	mi := &file_Tours_proto_tour_service_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRecensionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRecensionRequest) ProtoMessage() {}

func (x *CreateRecensionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Tours_proto_tour_service_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRecensionRequest.ProtoReflect.Descriptor instead.
func (*CreateRecensionRequest) Descriptor() ([]byte, []int) {
	return file_Tours_proto_tour_service_proto_rawDescGZIP(), []int{28}
}

func (x *CreateRecensionRequest) GetRecension() *Recension {
	if x != nil {
		return x.Recension
	}
	return nil
}

type RecensionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Recension     *Recension             `protobuf:"bytes,1,opt,name=recension,proto3" json:"recension,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecensionResponse) Reset() {
	*x = RecensionResponse{}
	mi := &file_Tours_proto_tour_service_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecensionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecensionResponse) ProtoMessage() {}

func (x *RecensionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Tours_proto_tour_service_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecensionResponse.ProtoReflect.Descriptor instead.
func (*RecensionResponse) Descriptor() ([]byte, []int) {
	return file_Tours_proto_tour_service_proto_rawDescGZIP(), []int{29}
}

func (x *RecensionResponse) GetRecension() *Recension {
	if x != nil {
		return x.Recension
	}
	return nil
}

type RecensionListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Recensions    []*Recension           `protobuf:"bytes,1,rep,name=recensions,proto3" json:"recensions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecensionListResponse) Reset() {
	*x = RecensionListResponse{}
	mi := &file_Tours_proto_tour_service_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecensionListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecensionListResponse) ProtoMessage() {}

func (x *RecensionListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Tours_proto_tour_service_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecensionListResponse.ProtoReflect.Descriptor instead.
func (*RecensionListResponse) Descriptor() ([]byte, []int) {
	return file_Tours_proto_tour_service_proto_rawDescGZIP(), []int{30}
}

func (x *RecensionListResponse) GetRecensions() []*Recension {
	if x != nil {
		return x.Recensions
	}
	return nil
}

var File_Tours_proto_tour_service_proto protoreflect.FileDescriptor

const file_Tours_proto_tour_service_proto_rawDesc = "" +
	"\n" +
	"\x1eTours/proto/tour_service.proto\x12\x04tour\"\x98\x03\n" +
	"\x04Tour\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bauthorId\x18\x02 \x01(\tR\bauthorId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x124\n" +
	"\n" +
	"difficulty\x18\x05 \x01(\x0e2\x14.tour.TourDifficultyR\n" +
	"difficulty\x12!\n" +
	"\x04tags\x18\x06 \x03(\x0e2\r.tour.TourTagR\x04tags\x12(\n" +
	"\x06status\x18\a \x01(\x0e2\x10.tour.TourStatusR\x06status\x12\x14\n" +
	"\x05price\x18\b \x01(\x02R\x05price\x12=\n" +
	"\vtravelTimes\x18\t \x03(\v2\x1b.tour.Tour.TravelTimesEntryR\vtravelTimes\x12\x16\n" +
	"\x06length\x18\n" +
	" \x01(\x02R\x06length\x1a>\n" +
	"\x10TravelTimesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x02R\x05value:\x028\x01\"\xd4\x01\n" +
	"\bKeyPoint\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06tourId\x18\x02 \x01(\tR\x06tourId\x12\x1c\n" +
	"\tlongitude\x18\x03 \x01(\x02R\tlongitude\x12\x1a\n" +
	"\blatitude\x18\x04 \x01(\x02R\blatitude\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12\x1a\n" +
	"\bimageUrl\x18\a \x01(\tR\bimageUrl\x12\x14\n" +
	"\x05order\x18\b \x01(\x03R\x05order\"K\n" +
	"\x0fTouristPosition\x12\x1a\n" +
	"\blatitude\x18\x01 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x02 \x01(\x01R\tlongitude\"[\n" +
	"\x11CompletedKeyPoint\x12\x1e\n" +
	"\n" +
	"keyPointId\x18\x01 \x01(\tR\n" +
	"keyPointId\x12&\n" +
	"\x0ecompletionTime\x18\x02 \x01(\tR\x0ecompletionTime\"\xe9\x02\n" +
	"\x15TourExecutionResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06tourId\x18\x02 \x01(\tR\x06tourId\x12\x1c\n" +
	"\ttouristId\x18\x03 \x01(\tR\ttouristId\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1c\n" +
	"\tstartTime\x18\x05 \x01(\tR\tstartTime\x12\"\n" +
	"\flastActivity\x18\x06 \x01(\tR\flastActivity\x12&\n" +
	"\x0ecompletionTime\x18\a \x01(\tR\x0ecompletionTime\x12G\n" +
	"\x12completedKeyPoints\x18\b \x03(\v2\x17.tour.CompletedKeyPointR\x12completedKeyPoints\x12?\n" +
	"\x0fcurrentPosition\x18\t \x01(\v2\x15.tour.TouristPositionR\x0fcurrentPosition\"{\n" +
	"\x10StartTourRequest\x12\x16\n" +
	"\x06tourId\x18\x01 \x01(\tR\x06tourId\x121\n" +
	"\bposition\x18\x02 \x01(\v2\x15.tour.TouristPositionR\bposition\x12\x1c\n" +
	"\ttouristId\x18\x03 \x01(\tR\ttouristId\"D\n" +
	"\x14TourExecutionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1c\n" +
	"\ttouristId\x18\x02 \x01(\tR\ttouristId\",\n" +
	"\x12ArchiveTourRequest\x12\x16\n" +
	"\x06tourId\x18\x01 \x01(\tR\x06tourId\"/\n" +
	"\x13ArchiveTourResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\",\n" +
	"\x12PublishTourRequest\x12\x16\n" +
	"\x06tourId\x18\x01 \x01(\tR\x06tourId\"/\n" +
	"\x13PublishTourResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\a\n" +
	"\x05Empty\"\xd9\x01\n" +
	"\tRecension\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bauthorId\x18\x02 \x01(\tR\bauthorId\x12\x16\n" +
	"\x06tourId\x18\x03 \x01(\tR\x06tourId\x12\x16\n" +
	"\x06rating\x18\x04 \x01(\x05R\x06rating\x12\x1c\n" +
	"\tvisitDate\x18\x05 \x01(\tR\tvisitDate\x12\x18\n" +
	"\acomment\x18\x06 \x01(\tR\acomment\x12\x1c\n" +
	"\tcreatedAt\x18\a \x01(\tR\tcreatedAt\x12\x1a\n" +
	"\bpictures\x18\b \x03(\tR\bpictures\"4\n" +
	"\x10TourListResponse\x12 \n" +
	"\x05tours\x18\x01 \x03(\v2\n" +
	".tour.TourR\x05tours\"\x1f\n" +
	"\rTourIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"d\n" +
	"\x14DetailedTourResponse\x12\x1e\n" +
	"\x04tour\x18\x01 \x01(\v2\n" +
	".tour.TourR\x04tour\x12,\n" +
	"\tkeyPoints\x18\x02 \x03(\v2\x0e.tour.KeyPointR\tkeyPoints\".\n" +
	"\fTourResponse\x12\x1e\n" +
	"\x04tour\x18\x01 \x01(\v2\n" +
	".tour.TourR\x04tour\"3\n" +
	"\x11CreateTourRequest\x12\x1e\n" +
	"\x04tour\x18\x01 \x01(\v2\n" +
	".tour.TourR\x04tour\"3\n" +
	"\x11UpdateTourRequest\x12\x1e\n" +
	"\x04tour\x18\x01 \x01(\v2\n" +
	".tour.TourR\x04tour\"4\n" +
	"\x12UpdateTourResponse\x12\x1e\n" +
	"\x04tour\x18\x01 \x01(\v2\n" +
	".tour.TourR\x04tour\"e\n" +
	"\x15CreateKeyPointRequest\x12*\n" +
	"\bkeyPoint\x18\x01 \x01(\v2\x0e.tour.KeyPointR\bkeyPoint\x12 \n" +
	"\vimageBase64\x18\x02 \x01(\tR\vimageBase64\"D\n" +
	"\x16CreateKeyPointResponse\x12*\n" +
	"\bkeyPoint\x18\x01 \x01(\v2\x0e.tour.KeyPointR\bkeyPoint\"C\n" +
	"\x15UpdateKeyPointRequest\x12*\n" +
	"\bkeyPoint\x18\x01 \x01(\v2\x0e.tour.KeyPointR\bkeyPoint\"D\n" +
	"\x16UpdateKeyPointResponse\x12*\n" +
	"\bkeyPoint\x18\x01 \x01(\v2\x0e.tour.KeyPointR\bkeyPoint\"7\n" +
	"\x15DeleteKeyPointRequest\x12\x1e\n" +
	"\n" +
	"keyPointId\x18\x01 \x01(\tR\n" +
	"keyPointId\"2\n" +
	"\x16DeleteKeyPointResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"x\n" +
	"\x15CheckProximityRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x121\n" +
	"\bposition\x18\x02 \x01(\v2\x15.tour.TouristPositionR\bposition\x12\x1c\n" +
	"\ttouristId\x18\x03 \x01(\tR\ttouristId\"4\n" +
	"\x14GetActiveTourRequest\x12\x1c\n" +
	"\ttouristId\x18\x01 \x01(\tR\ttouristId\"G\n" +
	"\x16CreateRecensionRequest\x12-\n" +
	"\trecension\x18\x01 \x01(\v2\x0f.tour.RecensionR\trecension\"B\n" +
	"\x11RecensionResponse\x12-\n" +
	"\trecension\x18\x01 \x01(\v2\x0f.tour.RecensionR\trecension\"H\n" +
	"\x15RecensionListResponse\x12/\n" +
	"\n" +
	"recensions\x18\x01 \x03(\v2\x0f.tour.RecensionR\n" +
	"recensions*0\n" +
	"\x0eTourDifficulty\x12\b\n" +
	"\x04EASY\x10\x00\x12\n" +
	"\n" +
	"\x06MEDIUM\x10\x01\x12\b\n" +
	"\x04HARD\x10\x02*\x84\x01\n" +
	"\aTourTag\x12\n" +
	"\n" +
	"\x06Nature\x10\x00\x12\x0e\n" +
	"\n" +
	"Historical\x10\x01\x12\r\n" +
	"\tAdventure\x10\x02\x12\f\n" +
	"\bCultural\x10\x03\x12\f\n" +
	"\bWildlife\x10\x04\x12\x0e\n" +
	"\n" +
	"Relaxation\x10\x05\x12\t\n" +
	"\x05Beach\x10\x06\x12\f\n" +
	"\bMountain\x10\a\x12\t\n" +
	"\x05Urban\x10\b*4\n" +
	"\n" +
	"TourStatus\x12\t\n" +
	"\x05DRAFT\x10\x00\x12\r\n" +
	"\tPUBLISHED\x10\x01\x12\f\n" +
	"\bARCHIVED\x10\x022\xa1\b\n" +
	"\vTourService\x122\n" +
	"\vGetAllTours\x12\v.tour.Empty\x1a\x16.tour.TourListResponse\x12>\n" +
	"\vGetTourByID\x12\x13.tour.TourIDRequest\x1a\x1a.tour.DetailedTourResponse\x129\n" +
	"\n" +
	"CreateTour\x12\x17.tour.CreateTourRequest\x1a\x12.tour.TourResponse\x12?\n" +
	"\n" +
	"UpdateTour\x12\x17.tour.UpdateTourRequest\x1a\x18.tour.UpdateTourResponse\x12K\n" +
	"\x0eCreateKeyPoint\x12\x1b.tour.CreateKeyPointRequest\x1a\x1c.tour.CreateKeyPointResponse\x12K\n" +
	"\x0eUpdateKeyPoint\x12\x1b.tour.UpdateKeyPointRequest\x1a\x1c.tour.UpdateKeyPointResponse\x12K\n" +
	"\x0eDeleteKeyPoint\x12\x1b.tour.DeleteKeyPointRequest\x1a\x1c.tour.DeleteKeyPointResponse\x12@\n" +
	"\tStartTour\x12\x16.tour.StartTourRequest\x1a\x1b.tour.TourExecutionResponse\x12J\n" +
	"\x0eCheckProximity\x12\x1b.tour.CheckProximityRequest\x1a\x1b.tour.TourExecutionResponse\x12F\n" +
	"\vAbandonTour\x12\x1a.tour.TourExecutionRequest\x1a\x1b.tour.TourExecutionResponse\x12H\n" +
	"\rGetActiveTour\x12\x1a.tour.GetActiveTourRequest\x1a\x1b.tour.TourExecutionResponse\x12H\n" +
	"\x0fCreateRecension\x12\x1c.tour.CreateRecensionRequest\x1a\x17.tour.RecensionResponse\x12I\n" +
	"\x15GetRecensionsByTourID\x12\x13.tour.TourIDRequest\x1a\x1b.tour.RecensionListResponse\x12B\n" +
	"\vPublishTour\x12\x18.tour.PublishTourRequest\x1a\x19.tour.PublishTourResponse\x12B\n" +
	"\vArchiveTour\x12\x18.tour.ArchiveTourRequest\x1a\x19.tour.ArchiveTourResponseB\x0fZ\r./Tours/protob\x06proto3"

var (
	file_Tours_proto_tour_service_proto_rawDescOnce sync.Once
	file_Tours_proto_tour_service_proto_rawDescData []byte
)

func file_Tours_proto_tour_service_proto_rawDescGZIP() []byte {
	file_Tours_proto_tour_service_proto_rawDescOnce.Do(func() {
		file_Tours_proto_tour_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_Tours_proto_tour_service_proto_rawDesc), len(file_Tours_proto_tour_service_proto_rawDesc)))
	})
	return file_Tours_proto_tour_service_proto_rawDescData
}

var file_Tours_proto_tour_service_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_Tours_proto_tour_service_proto_msgTypes = make([]protoimpl.MessageInfo, 32)
var file_Tours_proto_tour_service_proto_goTypes = []any{
	(TourDifficulty)(0),            // 0: tour.TourDifficulty
	(TourTag)(0),                   // 1: tour.TourTag
	(TourStatus)(0),                // 2: tour.TourStatus
	(*Tour)(nil),                   // 3: tour.Tour
	(*KeyPoint)(nil),               // 4: tour.KeyPoint
	(*TouristPosition)(nil),        // 5: tour.TouristPosition
	(*CompletedKeyPoint)(nil),      // 6: tour.CompletedKeyPoint
	(*TourExecutionResponse)(nil),  // 7: tour.TourExecutionResponse
	(*StartTourRequest)(nil),       // 8: tour.StartTourRequest
	(*TourExecutionRequest)(nil),   // 9: tour.TourExecutionRequest
	(*ArchiveTourRequest)(nil),     // 10: tour.ArchiveTourRequest
	(*ArchiveTourResponse)(nil),    // 11: tour.ArchiveTourResponse
	(*PublishTourRequest)(nil),     // 12: tour.PublishTourRequest
	(*PublishTourResponse)(nil),    // 13: tour.PublishTourResponse
	(*Empty)(nil),                  // 14: tour.Empty
	(*Recension)(nil),              // 15: tour.Recension
	(*TourListResponse)(nil),       // 16: tour.TourListResponse
	(*TourIDRequest)(nil),          // 17: tour.TourIDRequest
	(*DetailedTourResponse)(nil),   // 18: tour.DetailedTourResponse
	(*TourResponse)(nil),           // 19: tour.TourResponse
	(*CreateTourRequest)(nil),      // 20: tour.CreateTourRequest
	(*UpdateTourRequest)(nil),      // 21: tour.UpdateTourRequest
	(*UpdateTourResponse)(nil),     // 22: tour.UpdateTourResponse
	(*CreateKeyPointRequest)(nil),  // 23: tour.CreateKeyPointRequest
	(*CreateKeyPointResponse)(nil), // 24: tour.CreateKeyPointResponse
	(*UpdateKeyPointRequest)(nil),  // 25: tour.UpdateKeyPointRequest
	(*UpdateKeyPointResponse)(nil), // 26: tour.UpdateKeyPointResponse
	(*DeleteKeyPointRequest)(nil),  // 27: tour.DeleteKeyPointRequest
	(*DeleteKeyPointResponse)(nil), // 28: tour.DeleteKeyPointResponse
	(*CheckProximityRequest)(nil),  // 29: tour.CheckProximityRequest
	(*GetActiveTourRequest)(nil),   // 30: tour.GetActiveTourRequest
	(*CreateRecensionRequest)(nil), // 31: tour.CreateRecensionRequest
	(*RecensionResponse)(nil),      // 32: tour.RecensionResponse
	(*RecensionListResponse)(nil),  // 33: tour.RecensionListResponse
	nil,                            // 34: tour.Tour.TravelTimesEntry
}
var file_Tours_proto_tour_service_proto_depIdxs = []int32{
	0,  // 0: tour.Tour.difficulty:type_name -> tour.TourDifficulty
	1,  // 1: tour.Tour.tags:type_name -> tour.TourTag
	2,  // 2: tour.Tour.status:type_name -> tour.TourStatus
	34, // 3: tour.Tour.travelTimes:type_name -> tour.Tour.TravelTimesEntry
	6,  // 4: tour.TourExecutionResponse.completedKeyPoints:type_name -> tour.CompletedKeyPoint
	5,  // 5: tour.TourExecutionResponse.currentPosition:type_name -> tour.TouristPosition
	5,  // 6: tour.StartTourRequest.position:type_name -> tour.TouristPosition
	3,  // 7: tour.TourListResponse.tours:type_name -> tour.Tour
	3,  // 8: tour.DetailedTourResponse.tour:type_name -> tour.Tour
	4,  // 9: tour.DetailedTourResponse.keyPoints:type_name -> tour.KeyPoint
	3,  // 10: tour.TourResponse.tour:type_name -> tour.Tour
	3,  // 11: tour.CreateTourRequest.tour:type_name -> tour.Tour
	3,  // 12: tour.UpdateTourRequest.tour:type_name -> tour.Tour
	3,  // 13: tour.UpdateTourResponse.tour:type_name -> tour.Tour
	4,  // 14: tour.CreateKeyPointRequest.keyPoint:type_name -> tour.KeyPoint
	4,  // 15: tour.CreateKeyPointResponse.keyPoint:type_name -> tour.KeyPoint
	4,  // 16: tour.UpdateKeyPointRequest.keyPoint:type_name -> tour.KeyPoint
	4,  // 17: tour.UpdateKeyPointResponse.keyPoint:type_name -> tour.KeyPoint
	5,  // 18: tour.CheckProximityRequest.position:type_name -> tour.TouristPosition
	15, // 19: tour.CreateRecensionRequest.recension:type_name -> tour.Recension
	15, // 20: tour.RecensionResponse.recension:type_name -> tour.Recension
	15, // 21: tour.RecensionListResponse.recensions:type_name -> tour.Recension
	14, // 22: tour.TourService.GetAllTours:input_type -> tour.Empty
	17, // 23: tour.TourService.GetTourByID:input_type -> tour.TourIDRequest
	20, // 24: tour.TourService.CreateTour:input_type -> tour.CreateTourRequest
	21, // 25: tour.TourService.UpdateTour:input_type -> tour.UpdateTourRequest
	23, // 26: tour.TourService.CreateKeyPoint:input_type -> tour.CreateKeyPointRequest
	25, // 27: tour.TourService.UpdateKeyPoint:input_type -> tour.UpdateKeyPointRequest
	27, // 28: tour.TourService.DeleteKeyPoint:input_type -> tour.DeleteKeyPointRequest
	8,  // 29: tour.TourService.StartTour:input_type -> tour.StartTourRequest
	29, // 30: tour.TourService.CheckProximity:input_type -> tour.CheckProximityRequest
	9,  // 31: tour.TourService.AbandonTour:input_type -> tour.TourExecutionRequest
	30, // 32: tour.TourService.GetActiveTour:input_type -> tour.GetActiveTourRequest
	31, // 33: tour.TourService.CreateRecension:input_type -> tour.CreateRecensionRequest
	17, // 34: tour.TourService.GetRecensionsByTourID:input_type -> tour.TourIDRequest
	12, // 35: tour.TourService.PublishTour:input_type -> tour.PublishTourRequest
	10, // 36: tour.TourService.ArchiveTour:input_type -> tour.ArchiveTourRequest
	16, // 37: tour.TourService.GetAllTours:output_type -> tour.TourListResponse
	18, // 38: tour.TourService.GetTourByID:output_type -> tour.DetailedTourResponse
	19, // 39: tour.TourService.CreateTour:output_type -> tour.TourResponse
	22, // 40: tour.TourService.UpdateTour:output_type -> tour.UpdateTourResponse
	24, // 41: tour.TourService.CreateKeyPoint:output_type -> tour.CreateKeyPointResponse
	26, // 42: tour.TourService.UpdateKeyPoint:output_type -> tour.UpdateKeyPointResponse
	28, // 43: tour.TourService.DeleteKeyPoint:output_type -> tour.DeleteKeyPointResponse
	7,  // 44: tour.TourService.StartTour:output_type -> tour.TourExecutionResponse
	7,  // 45: tour.TourService.CheckProximity:output_type -> tour.TourExecutionResponse
	7,  // 46: tour.TourService.AbandonTour:output_type -> tour.TourExecutionResponse
	7,  // 47: tour.TourService.GetActiveTour:output_type -> tour.TourExecutionResponse
	32, // 48: tour.TourService.CreateRecension:output_type -> tour.RecensionResponse
	33, // 49: tour.TourService.GetRecensionsByTourID:output_type -> tour.RecensionListResponse
	13, // 50: tour.TourService.PublishTour:output_type -> tour.PublishTourResponse
	11, // 51: tour.TourService.ArchiveTour:output_type -> tour.ArchiveTourResponse
	37, // [37:52] is the sub-list for method output_type
	22, // [22:37] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_Tours_proto_tour_service_proto_init() }
func file_Tours_proto_tour_service_proto_init() {
	if File_Tours_proto_tour_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Tours_proto_tour_service_proto_rawDesc), len(file_Tours_proto_tour_service_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   32,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_Tours_proto_tour_service_proto_goTypes,
		DependencyIndexes: file_Tours_proto_tour_service_proto_depIdxs,
		EnumInfos:         file_Tours_proto_tour_service_proto_enumTypes,
		MessageInfos:      file_Tours_proto_tour_service_proto_msgTypes,
	}.Build()
	File_Tours_proto_tour_service_proto = out.File
	file_Tours_proto_tour_service_proto_goTypes = nil
	file_Tours_proto_tour_service_proto_depIdxs = nil
}
