// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.31.1
// source: Tours/proto/tour_service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TourDifficulty int32

const (
	TourDifficulty_EASY   TourDifficulty = 0
	TourDifficulty_MEDIUM TourDifficulty = 1
	TourDifficulty_HARD   TourDifficulty = 2
)

// Enum value maps for TourDifficulty.
var (
	TourDifficulty_name = map[int32]string{
		0: "EASY",
		1: "MEDIUM",
		2: "HARD",
	}
	TourDifficulty_value = map[string]int32{
		"EASY":   0,
		"MEDIUM": 1,
		"HARD":   2,
	}
)

func (x TourDifficulty) Enum() *TourDifficulty {
	p := new(TourDifficulty)
	*p = x
	return p
}

func (x TourDifficulty) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TourDifficulty) Descriptor() protoreflect.EnumDescriptor {
	return file_Tours_proto_tour_service_proto_enumTypes[0].Descriptor()
}

func (TourDifficulty) Type() protoreflect.EnumType {
	return &file_Tours_proto_tour_service_proto_enumTypes[0]
}

func (x TourDifficulty) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TourDifficulty.Descriptor instead.
func (TourDifficulty) EnumDescriptor() ([]byte, []int) {
	return file_Tours_proto_tour_service_proto_rawDescGZIP(), []int{0}
}

type TourTag int32

const (
	TourTag_NATURE     TourTag = 0
	TourTag_HISTORICAL TourTag = 1
	TourTag_ADVENTURE  TourTag = 2
	TourTag_CULTURAL   TourTag = 3
	TourTag_WILDLIFE   TourTag = 4
	TourTag_RELAXATION TourTag = 5
	TourTag_BEACH      TourTag = 6
	TourTag_MOUNTAIN   TourTag = 7
	TourTag_URBAN      TourTag = 8
)

// Enum value maps for TourTag.
var (
	TourTag_name = map[int32]string{
		0: "NATURE",
		1: "HISTORICAL",
		2: "ADVENTURE",
		3: "CULTURAL",
		4: "WILDLIFE",
		5: "RELAXATION",
		6: "BEACH",
		7: "MOUNTAIN",
		8: "URBAN",
	}
	TourTag_value = map[string]int32{
		"NATURE":     0,
		"HISTORICAL": 1,
		"ADVENTURE":  2,
		"CULTURAL":   3,
		"WILDLIFE":   4,
		"RELAXATION": 5,
		"BEACH":      6,
		"MOUNTAIN":   7,
		"URBAN":      8,
	}
)

func (x TourTag) Enum() *TourTag {
	p := new(TourTag)
	*p = x
	return p
}

func (x TourTag) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TourTag) Descriptor() protoreflect.EnumDescriptor {
	return file_Tours_proto_tour_service_proto_enumTypes[1].Descriptor()
}

func (TourTag) Type() protoreflect.EnumType {
	return &file_Tours_proto_tour_service_proto_enumTypes[1]
}

func (x TourTag) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TourTag.Descriptor instead.
func (TourTag) EnumDescriptor() ([]byte, []int) {
	return file_Tours_proto_tour_service_proto_rawDescGZIP(), []int{1}
}

type TourStatus int32

const (
	TourStatus_DRAFT TourStatus = 0
)

// Enum value maps for TourStatus.
var (
	TourStatus_name = map[int32]string{
		0: "DRAFT",
	}
	TourStatus_value = map[string]int32{
		"DRAFT": 0,
	}
)

func (x TourStatus) Enum() *TourStatus {
	p := new(TourStatus)
	*p = x
	return p
}

func (x TourStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TourStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_Tours_proto_tour_service_proto_enumTypes[2].Descriptor()
}

func (TourStatus) Type() protoreflect.EnumType {
	return &file_Tours_proto_tour_service_proto_enumTypes[2]
}

func (x TourStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TourStatus.Descriptor instead.
func (TourStatus) EnumDescriptor() ([]byte, []int) {
	return file_Tours_proto_tour_service_proto_rawDescGZIP(), []int{2}
}

type Tour struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AuthorId      string                 `protobuf:"bytes,2,opt,name=authorId,proto3" json:"authorId,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Difficulty    TourDifficulty         `protobuf:"varint,5,opt,name=difficulty,proto3,enum=tour.TourDifficulty" json:"difficulty,omitempty"`
	Tags          []TourTag              `protobuf:"varint,6,rep,packed,name=tags,proto3,enum=tour.TourTag" json:"tags,omitempty"`
	Status        TourStatus             `protobuf:"varint,7,opt,name=status,proto3,enum=tour.TourStatus" json:"status,omitempty"`
	Price         float32                `protobuf:"fixed32,8,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tour) Reset() {
	*x = Tour{}
	mi := &file_Tours_proto_tour_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tour) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tour) ProtoMessage() {}

func (x *Tour) ProtoReflect() protoreflect.Message {
	mi := &file_Tours_proto_tour_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tour.ProtoReflect.Descriptor instead.
func (*Tour) Descriptor() ([]byte, []int) {
	return file_Tours_proto_tour_service_proto_rawDescGZIP(), []int{0}
}

func (x *Tour) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Tour) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

func (x *Tour) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Tour) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Tour) GetDifficulty() TourDifficulty {
	if x != nil {
		return x.Difficulty
	}
	return TourDifficulty_EASY
}

func (x *Tour) GetTags() []TourTag {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Tour) GetStatus() TourStatus {
	if x != nil {
		return x.Status
	}
	return TourStatus_DRAFT
}

func (x *Tour) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_Tours_proto_tour_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_Tours_proto_tour_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_Tours_proto_tour_service_proto_rawDescGZIP(), []int{1}
}

type TourListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tours         []*Tour                `protobuf:"bytes,1,rep,name=tours,proto3" json:"tours,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TourListResponse) Reset() {
	*x = TourListResponse{}
	mi := &file_Tours_proto_tour_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TourListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TourListResponse) ProtoMessage() {}

func (x *TourListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Tours_proto_tour_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TourListResponse.ProtoReflect.Descriptor instead.
func (*TourListResponse) Descriptor() ([]byte, []int) {
	return file_Tours_proto_tour_service_proto_rawDescGZIP(), []int{2}
}

func (x *TourListResponse) GetTours() []*Tour {
	if x != nil {
		return x.Tours
	}
	return nil
}

type TourIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TourIDRequest) Reset() {
	*x = TourIDRequest{}
	mi := &file_Tours_proto_tour_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TourIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TourIDRequest) ProtoMessage() {}

func (x *TourIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Tours_proto_tour_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TourIDRequest.ProtoReflect.Descriptor instead.
func (*TourIDRequest) Descriptor() ([]byte, []int) {
	return file_Tours_proto_tour_service_proto_rawDescGZIP(), []int{3}
}

func (x *TourIDRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type TourResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tour          *Tour                  `protobuf:"bytes,1,opt,name=tour,proto3" json:"tour,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TourResponse) Reset() {
	*x = TourResponse{}
	mi := &file_Tours_proto_tour_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TourResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TourResponse) ProtoMessage() {}

func (x *TourResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Tours_proto_tour_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TourResponse.ProtoReflect.Descriptor instead.
func (*TourResponse) Descriptor() ([]byte, []int) {
	return file_Tours_proto_tour_service_proto_rawDescGZIP(), []int{4}
}

func (x *TourResponse) GetTour() *Tour {
	if x != nil {
		return x.Tour
	}
	return nil
}

type CreateTourRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tour          *Tour                  `protobuf:"bytes,1,opt,name=tour,proto3" json:"tour,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTourRequest) Reset() {
	*x = CreateTourRequest{}
	mi := &file_Tours_proto_tour_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTourRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTourRequest) ProtoMessage() {}

func (x *CreateTourRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Tours_proto_tour_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTourRequest.ProtoReflect.Descriptor instead.
func (*CreateTourRequest) Descriptor() ([]byte, []int) {
	return file_Tours_proto_tour_service_proto_rawDescGZIP(), []int{5}
}

func (x *CreateTourRequest) GetTour() *Tour {
	if x != nil {
		return x.Tour
	}
	return nil
}

var File_Tours_proto_tour_service_proto protoreflect.FileDescriptor

const file_Tours_proto_tour_service_proto_rawDesc = "" +
	"\n" +
	"\x1eTours/proto/tour_service.proto\x12\x04tour\"\x81\x02\n" +
	"\x04Tour\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bauthorId\x18\x02 \x01(\tR\bauthorId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x124\n" +
	"\n" +
	"difficulty\x18\x05 \x01(\x0e2\x14.tour.TourDifficultyR\n" +
	"difficulty\x12!\n" +
	"\x04tags\x18\x06 \x03(\x0e2\r.tour.TourTagR\x04tags\x12(\n" +
	"\x06status\x18\a \x01(\x0e2\x10.tour.TourStatusR\x06status\x12\x14\n" +
	"\x05price\x18\b \x01(\x02R\x05price\"\a\n" +
	"\x05Empty\"4\n" +
	"\x10TourListResponse\x12 \n" +
	"\x05tours\x18\x01 \x03(\v2\n" +
	".tour.TourR\x05tours\"\x1f\n" +
	"\rTourIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\".\n" +
	"\fTourResponse\x12\x1e\n" +
	"\x04tour\x18\x01 \x01(\v2\n" +
	".tour.TourR\x04tour\"3\n" +
	"\x11CreateTourRequest\x12\x1e\n" +
	"\x04tour\x18\x01 \x01(\v2\n" +
	".tour.TourR\x04tour*0\n" +
	"\x0eTourDifficulty\x12\b\n" +
	"\x04EASY\x10\x00\x12\n" +
	"\n" +
	"\x06MEDIUM\x10\x01\x12\b\n" +
	"\x04HARD\x10\x02*\x84\x01\n" +
	"\aTourTag\x12\n" +
	"\n" +
	"\x06NATURE\x10\x00\x12\x0e\n" +
	"\n" +
	"HISTORICAL\x10\x01\x12\r\n" +
	"\tADVENTURE\x10\x02\x12\f\n" +
	"\bCULTURAL\x10\x03\x12\f\n" +
	"\bWILDLIFE\x10\x04\x12\x0e\n" +
	"\n" +
	"RELAXATION\x10\x05\x12\t\n" +
	"\x05BEACH\x10\x06\x12\f\n" +
	"\bMOUNTAIN\x10\a\x12\t\n" +
	"\x05URBAN\x10\b*\x17\n" +
	"\n" +
	"TourStatus\x12\t\n" +
	"\x05DRAFT\x10\x002\xb4\x01\n" +
	"\vTourService\x122\n" +
	"\vGetAllTours\x12\v.tour.Empty\x1a\x16.tour.TourListResponse\x126\n" +
	"\vGetTourByID\x12\x13.tour.TourIDRequest\x1a\x12.tour.TourResponse\x129\n" +
	"\n" +
	"CreateTour\x12\x17.tour.CreateTourRequest\x1a\x12.tour.TourResponseB\x0fZ\r./Tours/protob\x06proto3"

var (
	file_Tours_proto_tour_service_proto_rawDescOnce sync.Once
	file_Tours_proto_tour_service_proto_rawDescData []byte
)

func file_Tours_proto_tour_service_proto_rawDescGZIP() []byte {
	file_Tours_proto_tour_service_proto_rawDescOnce.Do(func() {
		file_Tours_proto_tour_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_Tours_proto_tour_service_proto_rawDesc), len(file_Tours_proto_tour_service_proto_rawDesc)))
	})
	return file_Tours_proto_tour_service_proto_rawDescData
}

var file_Tours_proto_tour_service_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_Tours_proto_tour_service_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_Tours_proto_tour_service_proto_goTypes = []any{
	(TourDifficulty)(0),       // 0: tour.TourDifficulty
	(TourTag)(0),              // 1: tour.TourTag
	(TourStatus)(0),           // 2: tour.TourStatus
	(*Tour)(nil),              // 3: tour.Tour
	(*Empty)(nil),             // 4: tour.Empty
	(*TourListResponse)(nil),  // 5: tour.TourListResponse
	(*TourIDRequest)(nil),     // 6: tour.TourIDRequest
	(*TourResponse)(nil),      // 7: tour.TourResponse
	(*CreateTourRequest)(nil), // 8: tour.CreateTourRequest
}
var file_Tours_proto_tour_service_proto_depIdxs = []int32{
	0, // 0: tour.Tour.difficulty:type_name -> tour.TourDifficulty
	1, // 1: tour.Tour.tags:type_name -> tour.TourTag
	2, // 2: tour.Tour.status:type_name -> tour.TourStatus
	3, // 3: tour.TourListResponse.tours:type_name -> tour.Tour
	3, // 4: tour.TourResponse.tour:type_name -> tour.Tour
	3, // 5: tour.CreateTourRequest.tour:type_name -> tour.Tour
	4, // 6: tour.TourService.GetAllTours:input_type -> tour.Empty
	6, // 7: tour.TourService.GetTourByID:input_type -> tour.TourIDRequest
	8, // 8: tour.TourService.CreateTour:input_type -> tour.CreateTourRequest
	5, // 9: tour.TourService.GetAllTours:output_type -> tour.TourListResponse
	7, // 10: tour.TourService.GetTourByID:output_type -> tour.TourResponse
	7, // 11: tour.TourService.CreateTour:output_type -> tour.TourResponse
	9, // [9:12] is the sub-list for method output_type
	6, // [6:9] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_Tours_proto_tour_service_proto_init() }
func file_Tours_proto_tour_service_proto_init() {
	if File_Tours_proto_tour_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Tours_proto_tour_service_proto_rawDesc), len(file_Tours_proto_tour_service_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_Tours_proto_tour_service_proto_goTypes,
		DependencyIndexes: file_Tours_proto_tour_service_proto_depIdxs,
		EnumInfos:         file_Tours_proto_tour_service_proto_enumTypes,
		MessageInfos:      file_Tours_proto_tour_service_proto_msgTypes,
	}.Build()
	File_Tours_proto_tour_service_proto = out.File
	file_Tours_proto_tour_service_proto_goTypes = nil
	file_Tours_proto_tour_service_proto_depIdxs = nil
}
