// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.31.1
// source: Tours/proto/tour_service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TourDifficulty int32

const (
	TourDifficulty_EASY   TourDifficulty = 0
	TourDifficulty_MEDIUM TourDifficulty = 1
	TourDifficulty_HARD   TourDifficulty = 2
)

// Enum value maps for TourDifficulty.
var (
	TourDifficulty_name = map[int32]string{
		0: "EASY",
		1: "MEDIUM",
		2: "HARD",
	}
	TourDifficulty_value = map[string]int32{
		"EASY":   0,
		"MEDIUM": 1,
		"HARD":   2,
	}
)

func (x TourDifficulty) Enum() *TourDifficulty {
	p := new(TourDifficulty)
	*p = x
	return p
}

func (x TourDifficulty) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TourDifficulty) Descriptor() protoreflect.EnumDescriptor {
	return file_Tours_proto_tour_service_proto_enumTypes[0].Descriptor()
}

func (TourDifficulty) Type() protoreflect.EnumType {
	return &file_Tours_proto_tour_service_proto_enumTypes[0]
}

func (x TourDifficulty) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TourDifficulty.Descriptor instead.
func (TourDifficulty) EnumDescriptor() ([]byte, []int) {
	return file_Tours_proto_tour_service_proto_rawDescGZIP(), []int{0}
}

type TourTag int32

const (
	TourTag_Nature     TourTag = 0
	TourTag_Historical TourTag = 1
	TourTag_Adventure  TourTag = 2
	TourTag_Cultural   TourTag = 3
	TourTag_Wildlife   TourTag = 4
	TourTag_Relaxation TourTag = 5
	TourTag_Beach      TourTag = 6
	TourTag_Mountain   TourTag = 7
	TourTag_Urban      TourTag = 8
)

// Enum value maps for TourTag.
var (
	TourTag_name = map[int32]string{
		0: "Nature",
		1: "Historical",
		2: "Adventure",
		3: "Cultural",
		4: "Wildlife",
		5: "Relaxation",
		6: "Beach",
		7: "Mountain",
		8: "Urban",
	}
	TourTag_value = map[string]int32{
		"Nature":     0,
		"Historical": 1,
		"Adventure":  2,
		"Cultural":   3,
		"Wildlife":   4,
		"Relaxation": 5,
		"Beach":      6,
		"Mountain":   7,
		"Urban":      8,
	}
)

func (x TourTag) Enum() *TourTag {
	p := new(TourTag)
	*p = x
	return p
}

func (x TourTag) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TourTag) Descriptor() protoreflect.EnumDescriptor {
	return file_Tours_proto_tour_service_proto_enumTypes[1].Descriptor()
}

func (TourTag) Type() protoreflect.EnumType {
	return &file_Tours_proto_tour_service_proto_enumTypes[1]
}

func (x TourTag) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TourTag.Descriptor instead.
func (TourTag) EnumDescriptor() ([]byte, []int) {
	return file_Tours_proto_tour_service_proto_rawDescGZIP(), []int{1}
}

type TourStatus int32

const (
	TourStatus_DRAFT TourStatus = 0
)

// Enum value maps for TourStatus.
var (
	TourStatus_name = map[int32]string{
		0: "DRAFT",
	}
	TourStatus_value = map[string]int32{
		"DRAFT": 0,
	}
)

func (x TourStatus) Enum() *TourStatus {
	p := new(TourStatus)
	*p = x
	return p
}

func (x TourStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TourStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_Tours_proto_tour_service_proto_enumTypes[2].Descriptor()
}

func (TourStatus) Type() protoreflect.EnumType {
	return &file_Tours_proto_tour_service_proto_enumTypes[2]
}

func (x TourStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TourStatus.Descriptor instead.
func (TourStatus) EnumDescriptor() ([]byte, []int) {
	return file_Tours_proto_tour_service_proto_rawDescGZIP(), []int{2}
}

type Tour struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AuthorId      string                 `protobuf:"bytes,2,opt,name=authorId,proto3" json:"authorId,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Difficulty    TourDifficulty         `protobuf:"varint,5,opt,name=difficulty,proto3,enum=tour.TourDifficulty" json:"difficulty,omitempty"`
	Tags          []TourTag              `protobuf:"varint,6,rep,packed,name=tags,proto3,enum=tour.TourTag" json:"tags,omitempty"`
	Status        TourStatus             `protobuf:"varint,7,opt,name=status,proto3,enum=tour.TourStatus" json:"status,omitempty"`
	Price         float32                `protobuf:"fixed32,8,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tour) Reset() {
	*x = Tour{}
	mi := &file_Tours_proto_tour_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tour) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tour) ProtoMessage() {}

func (x *Tour) ProtoReflect() protoreflect.Message {
	mi := &file_Tours_proto_tour_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tour.ProtoReflect.Descriptor instead.
func (*Tour) Descriptor() ([]byte, []int) {
	return file_Tours_proto_tour_service_proto_rawDescGZIP(), []int{0}
}

func (x *Tour) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Tour) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

func (x *Tour) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Tour) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Tour) GetDifficulty() TourDifficulty {
	if x != nil {
		return x.Difficulty
	}
	return TourDifficulty_EASY
}

func (x *Tour) GetTags() []TourTag {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Tour) GetStatus() TourStatus {
	if x != nil {
		return x.Status
	}
	return TourStatus_DRAFT
}

func (x *Tour) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

type KeyPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TourId        string                 `protobuf:"bytes,2,opt,name=tourId,proto3" json:"tourId,omitempty"`
	Longitude     float32                `protobuf:"fixed32,3,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Latitude      float32                `protobuf:"fixed32,4,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Name          string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	ImageId       string                 `protobuf:"bytes,7,opt,name=imageId,proto3" json:"imageId,omitempty"`
	Order         int64                  `protobuf:"varint,8,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyPoint) Reset() {
	*x = KeyPoint{}
	mi := &file_Tours_proto_tour_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyPoint) ProtoMessage() {}

func (x *KeyPoint) ProtoReflect() protoreflect.Message {
	mi := &file_Tours_proto_tour_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyPoint.ProtoReflect.Descriptor instead.
func (*KeyPoint) Descriptor() ([]byte, []int) {
	return file_Tours_proto_tour_service_proto_rawDescGZIP(), []int{1}
}

func (x *KeyPoint) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *KeyPoint) GetTourId() string {
	if x != nil {
		return x.TourId
	}
	return ""
}

func (x *KeyPoint) GetLongitude() float32 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *KeyPoint) GetLatitude() float32 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *KeyPoint) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *KeyPoint) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *KeyPoint) GetImageId() string {
	if x != nil {
		return x.ImageId
	}
	return ""
}

func (x *KeyPoint) GetOrder() int64 {
	if x != nil {
		return x.Order
	}
	return 0
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_Tours_proto_tour_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_Tours_proto_tour_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_Tours_proto_tour_service_proto_rawDescGZIP(), []int{2}
}

type TourListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tours         []*Tour                `protobuf:"bytes,1,rep,name=tours,proto3" json:"tours,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TourListResponse) Reset() {
	*x = TourListResponse{}
	mi := &file_Tours_proto_tour_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TourListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TourListResponse) ProtoMessage() {}

func (x *TourListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Tours_proto_tour_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TourListResponse.ProtoReflect.Descriptor instead.
func (*TourListResponse) Descriptor() ([]byte, []int) {
	return file_Tours_proto_tour_service_proto_rawDescGZIP(), []int{3}
}

func (x *TourListResponse) GetTours() []*Tour {
	if x != nil {
		return x.Tours
	}
	return nil
}

type TourIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TourIDRequest) Reset() {
	*x = TourIDRequest{}
	mi := &file_Tours_proto_tour_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TourIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TourIDRequest) ProtoMessage() {}

func (x *TourIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Tours_proto_tour_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TourIDRequest.ProtoReflect.Descriptor instead.
func (*TourIDRequest) Descriptor() ([]byte, []int) {
	return file_Tours_proto_tour_service_proto_rawDescGZIP(), []int{4}
}

func (x *TourIDRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DetailedTourResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tour          *Tour                  `protobuf:"bytes,1,opt,name=tour,proto3" json:"tour,omitempty"`
	KeyPoints     []*KeyPoint            `protobuf:"bytes,2,rep,name=keyPoints,proto3" json:"keyPoints,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetailedTourResponse) Reset() {
	*x = DetailedTourResponse{}
	mi := &file_Tours_proto_tour_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetailedTourResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetailedTourResponse) ProtoMessage() {}

func (x *DetailedTourResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Tours_proto_tour_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetailedTourResponse.ProtoReflect.Descriptor instead.
func (*DetailedTourResponse) Descriptor() ([]byte, []int) {
	return file_Tours_proto_tour_service_proto_rawDescGZIP(), []int{5}
}

func (x *DetailedTourResponse) GetTour() *Tour {
	if x != nil {
		return x.Tour
	}
	return nil
}

func (x *DetailedTourResponse) GetKeyPoints() []*KeyPoint {
	if x != nil {
		return x.KeyPoints
	}
	return nil
}

type TourResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tour          *Tour                  `protobuf:"bytes,1,opt,name=tour,proto3" json:"tour,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TourResponse) Reset() {
	*x = TourResponse{}
	mi := &file_Tours_proto_tour_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TourResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TourResponse) ProtoMessage() {}

func (x *TourResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Tours_proto_tour_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TourResponse.ProtoReflect.Descriptor instead.
func (*TourResponse) Descriptor() ([]byte, []int) {
	return file_Tours_proto_tour_service_proto_rawDescGZIP(), []int{6}
}

func (x *TourResponse) GetTour() *Tour {
	if x != nil {
		return x.Tour
	}
	return nil
}

type CreateTourRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tour          *Tour                  `protobuf:"bytes,1,opt,name=tour,proto3" json:"tour,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTourRequest) Reset() {
	*x = CreateTourRequest{}
	mi := &file_Tours_proto_tour_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTourRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTourRequest) ProtoMessage() {}

func (x *CreateTourRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Tours_proto_tour_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTourRequest.ProtoReflect.Descriptor instead.
func (*CreateTourRequest) Descriptor() ([]byte, []int) {
	return file_Tours_proto_tour_service_proto_rawDescGZIP(), []int{7}
}

func (x *CreateTourRequest) GetTour() *Tour {
	if x != nil {
		return x.Tour
	}
	return nil
}

type CreateKeyPointRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyPoint      *KeyPoint              `protobuf:"bytes,1,opt,name=keyPoint,proto3" json:"keyPoint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateKeyPointRequest) Reset() {
	*x = CreateKeyPointRequest{}
	mi := &file_Tours_proto_tour_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateKeyPointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateKeyPointRequest) ProtoMessage() {}

func (x *CreateKeyPointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Tours_proto_tour_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateKeyPointRequest.ProtoReflect.Descriptor instead.
func (*CreateKeyPointRequest) Descriptor() ([]byte, []int) {
	return file_Tours_proto_tour_service_proto_rawDescGZIP(), []int{8}
}

func (x *CreateKeyPointRequest) GetKeyPoint() *KeyPoint {
	if x != nil {
		return x.KeyPoint
	}
	return nil
}

type CreateKeyPointResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyPoint      *KeyPoint              `protobuf:"bytes,1,opt,name=keyPoint,proto3" json:"keyPoint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateKeyPointResponse) Reset() {
	*x = CreateKeyPointResponse{}
	mi := &file_Tours_proto_tour_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateKeyPointResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateKeyPointResponse) ProtoMessage() {}

func (x *CreateKeyPointResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Tours_proto_tour_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateKeyPointResponse.ProtoReflect.Descriptor instead.
func (*CreateKeyPointResponse) Descriptor() ([]byte, []int) {
	return file_Tours_proto_tour_service_proto_rawDescGZIP(), []int{9}
}

func (x *CreateKeyPointResponse) GetKeyPoint() *KeyPoint {
	if x != nil {
		return x.KeyPoint
	}
	return nil
}

var File_Tours_proto_tour_service_proto protoreflect.FileDescriptor

const file_Tours_proto_tour_service_proto_rawDesc = "" +
	"\n" +
	"\x1eTours/proto/tour_service.proto\x12\x04tour\"\x81\x02\n" +
	"\x04Tour\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bauthorId\x18\x02 \x01(\tR\bauthorId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x124\n" +
	"\n" +
	"difficulty\x18\x05 \x01(\x0e2\x14.tour.TourDifficultyR\n" +
	"difficulty\x12!\n" +
	"\x04tags\x18\x06 \x03(\x0e2\r.tour.TourTagR\x04tags\x12(\n" +
	"\x06status\x18\a \x01(\x0e2\x10.tour.TourStatusR\x06status\x12\x14\n" +
	"\x05price\x18\b \x01(\x02R\x05price\"\xd2\x01\n" +
	"\bKeyPoint\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06tourId\x18\x02 \x01(\tR\x06tourId\x12\x1c\n" +
	"\tlongitude\x18\x03 \x01(\x02R\tlongitude\x12\x1a\n" +
	"\blatitude\x18\x04 \x01(\x02R\blatitude\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12\x18\n" +
	"\aimageId\x18\a \x01(\tR\aimageId\x12\x14\n" +
	"\x05order\x18\b \x01(\x03R\x05order\"\a\n" +
	"\x05Empty\"4\n" +
	"\x10TourListResponse\x12 \n" +
	"\x05tours\x18\x01 \x03(\v2\n" +
	".tour.TourR\x05tours\"\x1f\n" +
	"\rTourIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"d\n" +
	"\x14DetailedTourResponse\x12\x1e\n" +
	"\x04tour\x18\x01 \x01(\v2\n" +
	".tour.TourR\x04tour\x12,\n" +
	"\tkeyPoints\x18\x02 \x03(\v2\x0e.tour.KeyPointR\tkeyPoints\".\n" +
	"\fTourResponse\x12\x1e\n" +
	"\x04tour\x18\x01 \x01(\v2\n" +
	".tour.TourR\x04tour\"3\n" +
	"\x11CreateTourRequest\x12\x1e\n" +
	"\x04tour\x18\x01 \x01(\v2\n" +
	".tour.TourR\x04tour\"C\n" +
	"\x15CreateKeyPointRequest\x12*\n" +
	"\bkeyPoint\x18\x01 \x01(\v2\x0e.tour.KeyPointR\bkeyPoint\"D\n" +
	"\x16CreateKeyPointResponse\x12*\n" +
	"\bkeyPoint\x18\x01 \x01(\v2\x0e.tour.KeyPointR\bkeyPoint*0\n" +
	"\x0eTourDifficulty\x12\b\n" +
	"\x04EASY\x10\x00\x12\n" +
	"\n" +
	"\x06MEDIUM\x10\x01\x12\b\n" +
	"\x04HARD\x10\x02*\x84\x01\n" +
	"\aTourTag\x12\n" +
	"\n" +
	"\x06Nature\x10\x00\x12\x0e\n" +
	"\n" +
	"Historical\x10\x01\x12\r\n" +
	"\tAdventure\x10\x02\x12\f\n" +
	"\bCultural\x10\x03\x12\f\n" +
	"\bWildlife\x10\x04\x12\x0e\n" +
	"\n" +
	"Relaxation\x10\x05\x12\t\n" +
	"\x05Beach\x10\x06\x12\f\n" +
	"\bMountain\x10\a\x12\t\n" +
	"\x05Urban\x10\b*\x17\n" +
	"\n" +
	"TourStatus\x12\t\n" +
	"\x05DRAFT\x10\x002\x89\x02\n" +
	"\vTourService\x122\n" +
	"\vGetAllTours\x12\v.tour.Empty\x1a\x16.tour.TourListResponse\x12>\n" +
	"\vGetTourByID\x12\x13.tour.TourIDRequest\x1a\x1a.tour.DetailedTourResponse\x129\n" +
	"\n" +
	"CreateTour\x12\x17.tour.CreateTourRequest\x1a\x12.tour.TourResponse\x12K\n" +
	"\x0eCreateKeyPoint\x12\x1b.tour.CreateKeyPointRequest\x1a\x1c.tour.CreateKeyPointResponseB\x0fZ\r./Tours/protob\x06proto3"

var (
	file_Tours_proto_tour_service_proto_rawDescOnce sync.Once
	file_Tours_proto_tour_service_proto_rawDescData []byte
)

func file_Tours_proto_tour_service_proto_rawDescGZIP() []byte {
	file_Tours_proto_tour_service_proto_rawDescOnce.Do(func() {
		file_Tours_proto_tour_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_Tours_proto_tour_service_proto_rawDesc), len(file_Tours_proto_tour_service_proto_rawDesc)))
	})
	return file_Tours_proto_tour_service_proto_rawDescData
}

var file_Tours_proto_tour_service_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_Tours_proto_tour_service_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_Tours_proto_tour_service_proto_goTypes = []any{
	(TourDifficulty)(0),            // 0: tour.TourDifficulty
	(TourTag)(0),                   // 1: tour.TourTag
	(TourStatus)(0),                // 2: tour.TourStatus
	(*Tour)(nil),                   // 3: tour.Tour
	(*KeyPoint)(nil),               // 4: tour.KeyPoint
	(*Empty)(nil),                  // 5: tour.Empty
	(*TourListResponse)(nil),       // 6: tour.TourListResponse
	(*TourIDRequest)(nil),          // 7: tour.TourIDRequest
	(*DetailedTourResponse)(nil),   // 8: tour.DetailedTourResponse
	(*TourResponse)(nil),           // 9: tour.TourResponse
	(*CreateTourRequest)(nil),      // 10: tour.CreateTourRequest
	(*CreateKeyPointRequest)(nil),  // 11: tour.CreateKeyPointRequest
	(*CreateKeyPointResponse)(nil), // 12: tour.CreateKeyPointResponse
}
var file_Tours_proto_tour_service_proto_depIdxs = []int32{
	0,  // 0: tour.Tour.difficulty:type_name -> tour.TourDifficulty
	1,  // 1: tour.Tour.tags:type_name -> tour.TourTag
	2,  // 2: tour.Tour.status:type_name -> tour.TourStatus
	3,  // 3: tour.TourListResponse.tours:type_name -> tour.Tour
	3,  // 4: tour.DetailedTourResponse.tour:type_name -> tour.Tour
	4,  // 5: tour.DetailedTourResponse.keyPoints:type_name -> tour.KeyPoint
	3,  // 6: tour.TourResponse.tour:type_name -> tour.Tour
	3,  // 7: tour.CreateTourRequest.tour:type_name -> tour.Tour
	4,  // 8: tour.CreateKeyPointRequest.keyPoint:type_name -> tour.KeyPoint
	4,  // 9: tour.CreateKeyPointResponse.keyPoint:type_name -> tour.KeyPoint
	5,  // 10: tour.TourService.GetAllTours:input_type -> tour.Empty
	7,  // 11: tour.TourService.GetTourByID:input_type -> tour.TourIDRequest
	10, // 12: tour.TourService.CreateTour:input_type -> tour.CreateTourRequest
	11, // 13: tour.TourService.CreateKeyPoint:input_type -> tour.CreateKeyPointRequest
	6,  // 14: tour.TourService.GetAllTours:output_type -> tour.TourListResponse
	8,  // 15: tour.TourService.GetTourByID:output_type -> tour.DetailedTourResponse
	9,  // 16: tour.TourService.CreateTour:output_type -> tour.TourResponse
	12, // 17: tour.TourService.CreateKeyPoint:output_type -> tour.CreateKeyPointResponse
	14, // [14:18] is the sub-list for method output_type
	10, // [10:14] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_Tours_proto_tour_service_proto_init() }
func file_Tours_proto_tour_service_proto_init() {
	if File_Tours_proto_tour_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Tours_proto_tour_service_proto_rawDesc), len(file_Tours_proto_tour_service_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_Tours_proto_tour_service_proto_goTypes,
		DependencyIndexes: file_Tours_proto_tour_service_proto_depIdxs,
		EnumInfos:         file_Tours_proto_tour_service_proto_enumTypes,
		MessageInfos:      file_Tours_proto_tour_service_proto_msgTypes,
	}.Build()
	File_Tours_proto_tour_service_proto = out.File
	file_Tours_proto_tour_service_proto_goTypes = nil
	file_Tours_proto_tour_service_proto_depIdxs = nil
}
