// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.31.1
// source: blog_service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Blog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	AuthorId      string                 `protobuf:"bytes,4,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	Images        []string               `protobuf:"bytes,5,rep,name=images,proto3" json:"images,omitempty"`
	NumberOfLikes int32                  `protobuf:"varint,6,opt,name=number_of_likes,json=numberOfLikes,proto3" json:"number_of_likes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Blog) Reset() {
	*x = Blog{}
	mi := &file_blog_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Blog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Blog) ProtoMessage() {}

func (x *Blog) ProtoReflect() protoreflect.Message {
	mi := &file_blog_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Blog.ProtoReflect.Descriptor instead.
func (*Blog) Descriptor() ([]byte, []int) {
	return file_blog_service_proto_rawDescGZIP(), []int{0}
}

func (x *Blog) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Blog) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Blog) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Blog) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

func (x *Blog) GetImages() []string {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *Blog) GetNumberOfLikes() int32 {
	if x != nil {
		return x.NumberOfLikes
	}
	return 0
}

type BlogFull struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	AuthorId      string                 `protobuf:"bytes,4,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	Images        []string               `protobuf:"bytes,5,rep,name=images,proto3" json:"images,omitempty"`
	NumberOfLikes int32                  `protobuf:"varint,6,opt,name=number_of_likes,json=numberOfLikes,proto3" json:"number_of_likes,omitempty"`
	Comments      []*Comment             `protobuf:"bytes,7,rep,name=comments,proto3" json:"comments,omitempty"`
	Likes         []string               `protobuf:"bytes,8,rep,name=likes,proto3" json:"likes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlogFull) Reset() {
	*x = BlogFull{}
	mi := &file_blog_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlogFull) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlogFull) ProtoMessage() {}

func (x *BlogFull) ProtoReflect() protoreflect.Message {
	mi := &file_blog_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlogFull.ProtoReflect.Descriptor instead.
func (*BlogFull) Descriptor() ([]byte, []int) {
	return file_blog_service_proto_rawDescGZIP(), []int{1}
}

func (x *BlogFull) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BlogFull) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *BlogFull) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *BlogFull) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

func (x *BlogFull) GetImages() []string {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *BlogFull) GetNumberOfLikes() int32 {
	if x != nil {
		return x.NumberOfLikes
	}
	return 0
}

func (x *BlogFull) GetComments() []*Comment {
	if x != nil {
		return x.Comments
	}
	return nil
}

func (x *BlogFull) GetLikes() []string {
	if x != nil {
		return x.Likes
	}
	return nil
}

type Comment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	BlogId        string                 `protobuf:"bytes,2,opt,name=blog_id,json=blogId,proto3" json:"blog_id,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	LastModified  *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=last_modified,json=lastModified,proto3" json:"last_modified,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Comment) Reset() {
	*x = Comment{}
	mi := &file_blog_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Comment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Comment) ProtoMessage() {}

func (x *Comment) ProtoReflect() protoreflect.Message {
	mi := &file_blog_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Comment.ProtoReflect.Descriptor instead.
func (*Comment) Descriptor() ([]byte, []int) {
	return file_blog_service_proto_rawDescGZIP(), []int{2}
}

func (x *Comment) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Comment) GetBlogId() string {
	if x != nil {
		return x.BlogId
	}
	return ""
}

func (x *Comment) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Comment) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Comment) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Comment) GetLastModified() *timestamppb.Timestamp {
	if x != nil {
		return x.LastModified
	}
	return nil
}

type CreateBlogInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	AuthorId      string                 `protobuf:"bytes,3,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	Images        []string               `protobuf:"bytes,4,rep,name=images,proto3" json:"images,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBlogInput) Reset() {
	*x = CreateBlogInput{}
	mi := &file_blog_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBlogInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBlogInput) ProtoMessage() {}

func (x *CreateBlogInput) ProtoReflect() protoreflect.Message {
	mi := &file_blog_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBlogInput.ProtoReflect.Descriptor instead.
func (*CreateBlogInput) Descriptor() ([]byte, []int) {
	return file_blog_service_proto_rawDescGZIP(), []int{3}
}

func (x *CreateBlogInput) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateBlogInput) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CreateBlogInput) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

func (x *CreateBlogInput) GetImages() []string {
	if x != nil {
		return x.Images
	}
	return nil
}

type CreateCommentInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlogId        string                 `protobuf:"bytes,1,opt,name=blog_id,json=blogId,proto3" json:"blog_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCommentInput) Reset() {
	*x = CreateCommentInput{}
	mi := &file_blog_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCommentInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCommentInput) ProtoMessage() {}

func (x *CreateCommentInput) ProtoReflect() protoreflect.Message {
	mi := &file_blog_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCommentInput.ProtoReflect.Descriptor instead.
func (*CreateCommentInput) Descriptor() ([]byte, []int) {
	return file_blog_service_proto_rawDescGZIP(), []int{4}
}

func (x *CreateCommentInput) GetBlogId() string {
	if x != nil {
		return x.BlogId
	}
	return ""
}

func (x *CreateCommentInput) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateCommentInput) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type UpdateCommentInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CommentId     string                 `protobuf:"bytes,2,opt,name=comment_id,json=commentId,proto3" json:"comment_id,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	BlogId        string                 `protobuf:"bytes,4,opt,name=blog_id,json=blogId,proto3" json:"blog_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCommentInput) Reset() {
	*x = UpdateCommentInput{}
	mi := &file_blog_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCommentInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCommentInput) ProtoMessage() {}

func (x *UpdateCommentInput) ProtoReflect() protoreflect.Message {
	mi := &file_blog_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCommentInput.ProtoReflect.Descriptor instead.
func (*UpdateCommentInput) Descriptor() ([]byte, []int) {
	return file_blog_service_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateCommentInput) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateCommentInput) GetCommentId() string {
	if x != nil {
		return x.CommentId
	}
	return ""
}

func (x *UpdateCommentInput) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *UpdateCommentInput) GetBlogId() string {
	if x != nil {
		return x.BlogId
	}
	return ""
}

type CreateBlogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlogInput     *CreateBlogInput       `protobuf:"bytes,1,opt,name=blog_input,json=blogInput,proto3" json:"blog_input,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBlogRequest) Reset() {
	*x = CreateBlogRequest{}
	mi := &file_blog_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBlogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBlogRequest) ProtoMessage() {}

func (x *CreateBlogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blog_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBlogRequest.ProtoReflect.Descriptor instead.
func (*CreateBlogRequest) Descriptor() ([]byte, []int) {
	return file_blog_service_proto_rawDescGZIP(), []int{6}
}

func (x *CreateBlogRequest) GetBlogInput() *CreateBlogInput {
	if x != nil {
		return x.BlogInput
	}
	return nil
}

type CreateCommentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommentInput  *CreateCommentInput    `protobuf:"bytes,1,opt,name=comment_input,json=commentInput,proto3" json:"comment_input,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCommentRequest) Reset() {
	*x = CreateCommentRequest{}
	mi := &file_blog_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCommentRequest) ProtoMessage() {}

func (x *CreateCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blog_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCommentRequest.ProtoReflect.Descriptor instead.
func (*CreateCommentRequest) Descriptor() ([]byte, []int) {
	return file_blog_service_proto_rawDescGZIP(), []int{7}
}

func (x *CreateCommentRequest) GetCommentInput() *CreateCommentInput {
	if x != nil {
		return x.CommentInput
	}
	return nil
}

type UpdateCommentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommentInput  *UpdateCommentInput    `protobuf:"bytes,1,opt,name=comment_input,json=commentInput,proto3" json:"comment_input,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCommentRequest) Reset() {
	*x = UpdateCommentRequest{}
	mi := &file_blog_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCommentRequest) ProtoMessage() {}

func (x *UpdateCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blog_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCommentRequest.ProtoReflect.Descriptor instead.
func (*UpdateCommentRequest) Descriptor() ([]byte, []int) {
	return file_blog_service_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateCommentRequest) GetCommentInput() *UpdateCommentInput {
	if x != nil {
		return x.CommentInput
	}
	return nil
}

type CreateBlogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlogPost      *BlogFull              `protobuf:"bytes,1,opt,name=blog_post,json=blogPost,proto3" json:"blog_post,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBlogResponse) Reset() {
	*x = CreateBlogResponse{}
	mi := &file_blog_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBlogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBlogResponse) ProtoMessage() {}

func (x *CreateBlogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_blog_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBlogResponse.ProtoReflect.Descriptor instead.
func (*CreateBlogResponse) Descriptor() ([]byte, []int) {
	return file_blog_service_proto_rawDescGZIP(), []int{9}
}

func (x *CreateBlogResponse) GetBlogPost() *BlogFull {
	if x != nil {
		return x.BlogPost
	}
	return nil
}

type CreateCommentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Comment       *Comment               `protobuf:"bytes,1,opt,name=comment,proto3" json:"comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCommentResponse) Reset() {
	*x = CreateCommentResponse{}
	mi := &file_blog_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCommentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCommentResponse) ProtoMessage() {}

func (x *CreateCommentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_blog_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCommentResponse.ProtoReflect.Descriptor instead.
func (*CreateCommentResponse) Descriptor() ([]byte, []int) {
	return file_blog_service_proto_rawDescGZIP(), []int{10}
}

func (x *CreateCommentResponse) GetComment() *Comment {
	if x != nil {
		return x.Comment
	}
	return nil
}

type UpdateCommentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Comment       *Comment               `protobuf:"bytes,1,opt,name=comment,proto3" json:"comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCommentResponse) Reset() {
	*x = UpdateCommentResponse{}
	mi := &file_blog_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCommentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCommentResponse) ProtoMessage() {}

func (x *UpdateCommentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_blog_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCommentResponse.ProtoReflect.Descriptor instead.
func (*UpdateCommentResponse) Descriptor() ([]byte, []int) {
	return file_blog_service_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateCommentResponse) GetComment() *Comment {
	if x != nil {
		return x.Comment
	}
	return nil
}

type GetBlogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlogRequest) Reset() {
	*x = GetBlogRequest{}
	mi := &file_blog_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlogRequest) ProtoMessage() {}

func (x *GetBlogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blog_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlogRequest.ProtoReflect.Descriptor instead.
func (*GetBlogRequest) Descriptor() ([]byte, []int) {
	return file_blog_service_proto_rawDescGZIP(), []int{12}
}

func (x *GetBlogRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetBlogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlogPost      *BlogFull              `protobuf:"bytes,1,opt,name=blog_post,json=blogPost,proto3" json:"blog_post,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlogResponse) Reset() {
	*x = GetBlogResponse{}
	mi := &file_blog_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlogResponse) ProtoMessage() {}

func (x *GetBlogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_blog_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlogResponse.ProtoReflect.Descriptor instead.
func (*GetBlogResponse) Descriptor() ([]byte, []int) {
	return file_blog_service_proto_rawDescGZIP(), []int{13}
}

func (x *GetBlogResponse) GetBlogPost() *BlogFull {
	if x != nil {
		return x.BlogPost
	}
	return nil
}

type UpdateBlogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlogPost      *Blog                  `protobuf:"bytes,1,opt,name=blog_post,json=blogPost,proto3" json:"blog_post,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBlogRequest) Reset() {
	*x = UpdateBlogRequest{}
	mi := &file_blog_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBlogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBlogRequest) ProtoMessage() {}

func (x *UpdateBlogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blog_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBlogRequest.ProtoReflect.Descriptor instead.
func (*UpdateBlogRequest) Descriptor() ([]byte, []int) {
	return file_blog_service_proto_rawDescGZIP(), []int{14}
}

func (x *UpdateBlogRequest) GetBlogPost() *Blog {
	if x != nil {
		return x.BlogPost
	}
	return nil
}

type UpdateBlogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlogPost      *Blog                  `protobuf:"bytes,1,opt,name=blog_post,json=blogPost,proto3" json:"blog_post,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBlogResponse) Reset() {
	*x = UpdateBlogResponse{}
	mi := &file_blog_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBlogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBlogResponse) ProtoMessage() {}

func (x *UpdateBlogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_blog_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBlogResponse.ProtoReflect.Descriptor instead.
func (*UpdateBlogResponse) Descriptor() ([]byte, []int) {
	return file_blog_service_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateBlogResponse) GetBlogPost() *Blog {
	if x != nil {
		return x.BlogPost
	}
	return nil
}

type DeleteBlogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBlogRequest) Reset() {
	*x = DeleteBlogRequest{}
	mi := &file_blog_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBlogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBlogRequest) ProtoMessage() {}

func (x *DeleteBlogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blog_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBlogRequest.ProtoReflect.Descriptor instead.
func (*DeleteBlogRequest) Descriptor() ([]byte, []int) {
	return file_blog_service_proto_rawDescGZIP(), []int{16}
}

func (x *DeleteBlogRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteBlogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBlogResponse) Reset() {
	*x = DeleteBlogResponse{}
	mi := &file_blog_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBlogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBlogResponse) ProtoMessage() {}

func (x *DeleteBlogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_blog_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBlogResponse.ProtoReflect.Descriptor instead.
func (*DeleteBlogResponse) Descriptor() ([]byte, []int) {
	return file_blog_service_proto_rawDescGZIP(), []int{17}
}

func (x *DeleteBlogResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetAllBlogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllBlogsRequest) Reset() {
	*x = GetAllBlogsRequest{}
	mi := &file_blog_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllBlogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllBlogsRequest) ProtoMessage() {}

func (x *GetAllBlogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blog_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllBlogsRequest.ProtoReflect.Descriptor instead.
func (*GetAllBlogsRequest) Descriptor() ([]byte, []int) {
	return file_blog_service_proto_rawDescGZIP(), []int{18}
}

type GetFeedForUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFeedForUserRequest) Reset() {
	*x = GetFeedForUserRequest{}
	mi := &file_blog_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFeedForUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFeedForUserRequest) ProtoMessage() {}

func (x *GetFeedForUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blog_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFeedForUserRequest.ProtoReflect.Descriptor instead.
func (*GetFeedForUserRequest) Descriptor() ([]byte, []int) {
	return file_blog_service_proto_rawDescGZIP(), []int{19}
}

func (x *GetFeedForUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetAllBlogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Blogs         []*Blog                `protobuf:"bytes,1,rep,name=blogs,proto3" json:"blogs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllBlogsResponse) Reset() {
	*x = GetAllBlogsResponse{}
	mi := &file_blog_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllBlogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllBlogsResponse) ProtoMessage() {}

func (x *GetAllBlogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_blog_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllBlogsResponse.ProtoReflect.Descriptor instead.
func (*GetAllBlogsResponse) Descriptor() ([]byte, []int) {
	return file_blog_service_proto_rawDescGZIP(), []int{20}
}

func (x *GetAllBlogsResponse) GetBlogs() []*Blog {
	if x != nil {
		return x.Blogs
	}
	return nil
}

type LikeBlogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlogId        string                 `protobuf:"bytes,1,opt,name=blog_id,json=blogId,proto3" json:"blog_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikeBlogRequest) Reset() {
	*x = LikeBlogRequest{}
	mi := &file_blog_service_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikeBlogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeBlogRequest) ProtoMessage() {}

func (x *LikeBlogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blog_service_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeBlogRequest.ProtoReflect.Descriptor instead.
func (*LikeBlogRequest) Descriptor() ([]byte, []int) {
	return file_blog_service_proto_rawDescGZIP(), []int{21}
}

func (x *LikeBlogRequest) GetBlogId() string {
	if x != nil {
		return x.BlogId
	}
	return ""
}

func (x *LikeBlogRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type LikeBlogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlogPost      *BlogFull              `protobuf:"bytes,1,opt,name=blog_post,json=blogPost,proto3" json:"blog_post,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikeBlogResponse) Reset() {
	*x = LikeBlogResponse{}
	mi := &file_blog_service_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikeBlogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeBlogResponse) ProtoMessage() {}

func (x *LikeBlogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_blog_service_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeBlogResponse.ProtoReflect.Descriptor instead.
func (*LikeBlogResponse) Descriptor() ([]byte, []int) {
	return file_blog_service_proto_rawDescGZIP(), []int{22}
}

func (x *LikeBlogResponse) GetBlogPost() *BlogFull {
	if x != nil {
		return x.BlogPost
	}
	return nil
}

var File_blog_service_proto protoreflect.FileDescriptor

const file_blog_service_proto_rawDesc = "" +
	"\n" +
	"\x12blog_service.proto\x12\x04blog\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa3\x01\n" +
	"\x04Blog\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x1b\n" +
	"\tauthor_id\x18\x04 \x01(\tR\bauthorId\x12\x16\n" +
	"\x06images\x18\x05 \x03(\tR\x06images\x12&\n" +
	"\x0fnumber_of_likes\x18\x06 \x01(\x05R\rnumberOfLikes\"\xe8\x01\n" +
	"\bBlogFull\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x1b\n" +
	"\tauthor_id\x18\x04 \x01(\tR\bauthorId\x12\x16\n" +
	"\x06images\x18\x05 \x03(\tR\x06images\x12&\n" +
	"\x0fnumber_of_likes\x18\x06 \x01(\x05R\rnumberOfLikes\x12)\n" +
	"\bcomments\x18\a \x03(\v2\r.blog.CommentR\bcomments\x12\x14\n" +
	"\x05likes\x18\b \x03(\tR\x05likes\"\xe1\x01\n" +
	"\aComment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\ablog_id\x18\x02 \x01(\tR\x06blogId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12?\n" +
	"\rlast_modified\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\flastModified\"v\n" +
	"\x0fCreateBlogInput\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x1b\n" +
	"\tauthor_id\x18\x03 \x01(\tR\bauthorId\x12\x16\n" +
	"\x06images\x18\x04 \x03(\tR\x06images\"`\n" +
	"\x12CreateCommentInput\x12\x17\n" +
	"\ablog_id\x18\x01 \x01(\tR\x06blogId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\"\x7f\n" +
	"\x12UpdateCommentInput\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"comment_id\x18\x02 \x01(\tR\tcommentId\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x17\n" +
	"\ablog_id\x18\x04 \x01(\tR\x06blogId\"I\n" +
	"\x11CreateBlogRequest\x124\n" +
	"\n" +
	"blog_input\x18\x01 \x01(\v2\x15.blog.CreateBlogInputR\tblogInput\"U\n" +
	"\x14CreateCommentRequest\x12=\n" +
	"\rcomment_input\x18\x01 \x01(\v2\x18.blog.CreateCommentInputR\fcommentInput\"U\n" +
	"\x14UpdateCommentRequest\x12=\n" +
	"\rcomment_input\x18\x01 \x01(\v2\x18.blog.UpdateCommentInputR\fcommentInput\"A\n" +
	"\x12CreateBlogResponse\x12+\n" +
	"\tblog_post\x18\x01 \x01(\v2\x0e.blog.BlogFullR\bblogPost\"@\n" +
	"\x15CreateCommentResponse\x12'\n" +
	"\acomment\x18\x01 \x01(\v2\r.blog.CommentR\acomment\"@\n" +
	"\x15UpdateCommentResponse\x12'\n" +
	"\acomment\x18\x01 \x01(\v2\r.blog.CommentR\acomment\" \n" +
	"\x0eGetBlogRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\">\n" +
	"\x0fGetBlogResponse\x12+\n" +
	"\tblog_post\x18\x01 \x01(\v2\x0e.blog.BlogFullR\bblogPost\"<\n" +
	"\x11UpdateBlogRequest\x12'\n" +
	"\tblog_post\x18\x01 \x01(\v2\n" +
	".blog.BlogR\bblogPost\"=\n" +
	"\x12UpdateBlogResponse\x12'\n" +
	"\tblog_post\x18\x01 \x01(\v2\n" +
	".blog.BlogR\bblogPost\"#\n" +
	"\x11DeleteBlogRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\".\n" +
	"\x12DeleteBlogResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x14\n" +
	"\x12GetAllBlogsRequest\"/\n" +
	"\x15GetFeedForUserRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\"7\n" +
	"\x13GetAllBlogsResponse\x12 \n" +
	"\x05blogs\x18\x01 \x03(\v2\n" +
	".blog.BlogR\x05blogs\"C\n" +
	"\x0fLikeBlogRequest\x12\x17\n" +
	"\ablog_id\x18\x01 \x01(\tR\x06blogId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"?\n" +
	"\x10LikeBlogResponse\x12+\n" +
	"\tblog_post\x18\x01 \x01(\v2\x0e.blog.BlogFullR\bblogPost2\xa4\x04\n" +
	"\vBlogService\x12?\n" +
	"\n" +
	"CreateBlog\x12\x17.blog.CreateBlogRequest\x1a\x18.blog.CreateBlogResponse\x129\n" +
	"\bLikeBlog\x12\x15.blog.LikeBlogRequest\x1a\x16.blog.LikeBlogResponse\x12;\n" +
	"\n" +
	"UnlikeBlog\x12\x15.blog.LikeBlogRequest\x1a\x16.blog.LikeBlogResponse\x12B\n" +
	"\vGetAllBlogs\x12\x18.blog.GetAllBlogsRequest\x1a\x19.blog.GetAllBlogsResponse\x12:\n" +
	"\vGetBlogById\x12\x14.blog.GetBlogRequest\x1a\x15.blog.GetBlogResponse\x12H\n" +
	"\x0eGetFeedForUser\x12\x1b.blog.GetFeedForUserRequest\x1a\x19.blog.GetAllBlogsResponse\x12H\n" +
	"\rCreateComment\x12\x1a.blog.CreateCommentRequest\x1a\x1b.blog.CreateCommentResponse\x12H\n" +
	"\rUpdateComment\x12\x1a.blog.UpdateCommentRequest\x1a\x1b.blog.UpdateCommentResponseB\n" +
	"Z\b../protob\x06proto3"

var (
	file_blog_service_proto_rawDescOnce sync.Once
	file_blog_service_proto_rawDescData []byte
)

func file_blog_service_proto_rawDescGZIP() []byte {
	file_blog_service_proto_rawDescOnce.Do(func() {
		file_blog_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_blog_service_proto_rawDesc), len(file_blog_service_proto_rawDesc)))
	})
	return file_blog_service_proto_rawDescData
}

var file_blog_service_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_blog_service_proto_goTypes = []any{
	(*Blog)(nil),                  // 0: blog.Blog
	(*BlogFull)(nil),              // 1: blog.BlogFull
	(*Comment)(nil),               // 2: blog.Comment
	(*CreateBlogInput)(nil),       // 3: blog.CreateBlogInput
	(*CreateCommentInput)(nil),    // 4: blog.CreateCommentInput
	(*UpdateCommentInput)(nil),    // 5: blog.UpdateCommentInput
	(*CreateBlogRequest)(nil),     // 6: blog.CreateBlogRequest
	(*CreateCommentRequest)(nil),  // 7: blog.CreateCommentRequest
	(*UpdateCommentRequest)(nil),  // 8: blog.UpdateCommentRequest
	(*CreateBlogResponse)(nil),    // 9: blog.CreateBlogResponse
	(*CreateCommentResponse)(nil), // 10: blog.CreateCommentResponse
	(*UpdateCommentResponse)(nil), // 11: blog.UpdateCommentResponse
	(*GetBlogRequest)(nil),        // 12: blog.GetBlogRequest
	(*GetBlogResponse)(nil),       // 13: blog.GetBlogResponse
	(*UpdateBlogRequest)(nil),     // 14: blog.UpdateBlogRequest
	(*UpdateBlogResponse)(nil),    // 15: blog.UpdateBlogResponse
	(*DeleteBlogRequest)(nil),     // 16: blog.DeleteBlogRequest
	(*DeleteBlogResponse)(nil),    // 17: blog.DeleteBlogResponse
	(*GetAllBlogsRequest)(nil),    // 18: blog.GetAllBlogsRequest
	(*GetFeedForUserRequest)(nil), // 19: blog.GetFeedForUserRequest
	(*GetAllBlogsResponse)(nil),   // 20: blog.GetAllBlogsResponse
	(*LikeBlogRequest)(nil),       // 21: blog.LikeBlogRequest
	(*LikeBlogResponse)(nil),      // 22: blog.LikeBlogResponse
	(*timestamppb.Timestamp)(nil), // 23: google.protobuf.Timestamp
}
var file_blog_service_proto_depIdxs = []int32{
	2,  // 0: blog.BlogFull.comments:type_name -> blog.Comment
	23, // 1: blog.Comment.created_at:type_name -> google.protobuf.Timestamp
	23, // 2: blog.Comment.last_modified:type_name -> google.protobuf.Timestamp
	3,  // 3: blog.CreateBlogRequest.blog_input:type_name -> blog.CreateBlogInput
	4,  // 4: blog.CreateCommentRequest.comment_input:type_name -> blog.CreateCommentInput
	5,  // 5: blog.UpdateCommentRequest.comment_input:type_name -> blog.UpdateCommentInput
	1,  // 6: blog.CreateBlogResponse.blog_post:type_name -> blog.BlogFull
	2,  // 7: blog.CreateCommentResponse.comment:type_name -> blog.Comment
	2,  // 8: blog.UpdateCommentResponse.comment:type_name -> blog.Comment
	1,  // 9: blog.GetBlogResponse.blog_post:type_name -> blog.BlogFull
	0,  // 10: blog.UpdateBlogRequest.blog_post:type_name -> blog.Blog
	0,  // 11: blog.UpdateBlogResponse.blog_post:type_name -> blog.Blog
	0,  // 12: blog.GetAllBlogsResponse.blogs:type_name -> blog.Blog
	1,  // 13: blog.LikeBlogResponse.blog_post:type_name -> blog.BlogFull
	6,  // 14: blog.BlogService.CreateBlog:input_type -> blog.CreateBlogRequest
	21, // 15: blog.BlogService.LikeBlog:input_type -> blog.LikeBlogRequest
	21, // 16: blog.BlogService.UnlikeBlog:input_type -> blog.LikeBlogRequest
	18, // 17: blog.BlogService.GetAllBlogs:input_type -> blog.GetAllBlogsRequest
	12, // 18: blog.BlogService.GetBlogById:input_type -> blog.GetBlogRequest
	19, // 19: blog.BlogService.GetFeedForUser:input_type -> blog.GetFeedForUserRequest
	7,  // 20: blog.BlogService.CreateComment:input_type -> blog.CreateCommentRequest
	8,  // 21: blog.BlogService.UpdateComment:input_type -> blog.UpdateCommentRequest
	9,  // 22: blog.BlogService.CreateBlog:output_type -> blog.CreateBlogResponse
	22, // 23: blog.BlogService.LikeBlog:output_type -> blog.LikeBlogResponse
	22, // 24: blog.BlogService.UnlikeBlog:output_type -> blog.LikeBlogResponse
	20, // 25: blog.BlogService.GetAllBlogs:output_type -> blog.GetAllBlogsResponse
	13, // 26: blog.BlogService.GetBlogById:output_type -> blog.GetBlogResponse
	20, // 27: blog.BlogService.GetFeedForUser:output_type -> blog.GetAllBlogsResponse
	10, // 28: blog.BlogService.CreateComment:output_type -> blog.CreateCommentResponse
	11, // 29: blog.BlogService.UpdateComment:output_type -> blog.UpdateCommentResponse
	22, // [22:30] is the sub-list for method output_type
	14, // [14:22] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_blog_service_proto_init() }
func file_blog_service_proto_init() {
	if File_blog_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_blog_service_proto_rawDesc), len(file_blog_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_blog_service_proto_goTypes,
		DependencyIndexes: file_blog_service_proto_depIdxs,
		MessageInfos:      file_blog_service_proto_msgTypes,
	}.Build()
	File_blog_service_proto = out.File
	file_blog_service_proto_goTypes = nil
	file_blog_service_proto_depIdxs = nil
}
