// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.31.1
// source: proto/stakeholder_service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Definisanje Stakeholder poruke
type Stakeholder struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Stakeholder) Reset() {
	*x = Stakeholder{}
	mi := &file_proto_stakeholder_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Stakeholder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stakeholder) ProtoMessage() {}

func (x *Stakeholder) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stakeholder_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stakeholder.ProtoReflect.Descriptor instead.
func (*Stakeholder) Descriptor() ([]byte, []int) {
	return file_proto_stakeholder_service_proto_rawDescGZIP(), []int{0}
}

func (x *Stakeholder) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Stakeholder) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Stakeholder) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

// Poruke za operacije
type CreateStakeholderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stakeholder   *Stakeholder           `protobuf:"bytes,1,opt,name=stakeholder,proto3" json:"stakeholder,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateStakeholderRequest) Reset() {
	*x = CreateStakeholderRequest{}
	mi := &file_proto_stakeholder_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateStakeholderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStakeholderRequest) ProtoMessage() {}

func (x *CreateStakeholderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stakeholder_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStakeholderRequest.ProtoReflect.Descriptor instead.
func (*CreateStakeholderRequest) Descriptor() ([]byte, []int) {
	return file_proto_stakeholder_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateStakeholderRequest) GetStakeholder() *Stakeholder {
	if x != nil {
		return x.Stakeholder
	}
	return nil
}

type CreateStakeholderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stakeholder   *Stakeholder           `protobuf:"bytes,1,opt,name=stakeholder,proto3" json:"stakeholder,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateStakeholderResponse) Reset() {
	*x = CreateStakeholderResponse{}
	mi := &file_proto_stakeholder_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateStakeholderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStakeholderResponse) ProtoMessage() {}

func (x *CreateStakeholderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stakeholder_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStakeholderResponse.ProtoReflect.Descriptor instead.
func (*CreateStakeholderResponse) Descriptor() ([]byte, []int) {
	return file_proto_stakeholder_service_proto_rawDescGZIP(), []int{2}
}

func (x *CreateStakeholderResponse) GetStakeholder() *Stakeholder {
	if x != nil {
		return x.Stakeholder
	}
	return nil
}

type GetStakeholderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStakeholderRequest) Reset() {
	*x = GetStakeholderRequest{}
	mi := &file_proto_stakeholder_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStakeholderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStakeholderRequest) ProtoMessage() {}

func (x *GetStakeholderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stakeholder_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStakeholderRequest.ProtoReflect.Descriptor instead.
func (*GetStakeholderRequest) Descriptor() ([]byte, []int) {
	return file_proto_stakeholder_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetStakeholderRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetStakeholderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stakeholder   *Stakeholder           `protobuf:"bytes,1,opt,name=stakeholder,proto3" json:"stakeholder,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStakeholderResponse) Reset() {
	*x = GetStakeholderResponse{}
	mi := &file_proto_stakeholder_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStakeholderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStakeholderResponse) ProtoMessage() {}

func (x *GetStakeholderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stakeholder_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStakeholderResponse.ProtoReflect.Descriptor instead.
func (*GetStakeholderResponse) Descriptor() ([]byte, []int) {
	return file_proto_stakeholder_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetStakeholderResponse) GetStakeholder() *Stakeholder {
	if x != nil {
		return x.Stakeholder
	}
	return nil
}

type GetAllStakeholdersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllStakeholdersRequest) Reset() {
	*x = GetAllStakeholdersRequest{}
	mi := &file_proto_stakeholder_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllStakeholdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllStakeholdersRequest) ProtoMessage() {}

func (x *GetAllStakeholdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stakeholder_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllStakeholdersRequest.ProtoReflect.Descriptor instead.
func (*GetAllStakeholdersRequest) Descriptor() ([]byte, []int) {
	return file_proto_stakeholder_service_proto_rawDescGZIP(), []int{5}
}

type GetAllStakeholdersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stakeholders  []*Stakeholder         `protobuf:"bytes,1,rep,name=stakeholders,proto3" json:"stakeholders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllStakeholdersResponse) Reset() {
	*x = GetAllStakeholdersResponse{}
	mi := &file_proto_stakeholder_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllStakeholdersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllStakeholdersResponse) ProtoMessage() {}

func (x *GetAllStakeholdersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stakeholder_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllStakeholdersResponse.ProtoReflect.Descriptor instead.
func (*GetAllStakeholdersResponse) Descriptor() ([]byte, []int) {
	return file_proto_stakeholder_service_proto_rawDescGZIP(), []int{6}
}

func (x *GetAllStakeholdersResponse) GetStakeholders() []*Stakeholder {
	if x != nil {
		return x.Stakeholders
	}
	return nil
}

var File_proto_stakeholder_service_proto protoreflect.FileDescriptor

const file_proto_stakeholder_service_proto_rawDesc = "" +
	"\n" +
	"\x1fproto/stakeholder_service.proto\x12\vstakeholder\"G\n" +
	"\vStakeholder\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\"V\n" +
	"\x18CreateStakeholderRequest\x12:\n" +
	"\vstakeholder\x18\x01 \x01(\v2\x18.stakeholder.StakeholderR\vstakeholder\"W\n" +
	"\x19CreateStakeholderResponse\x12:\n" +
	"\vstakeholder\x18\x01 \x01(\v2\x18.stakeholder.StakeholderR\vstakeholder\"'\n" +
	"\x15GetStakeholderRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"T\n" +
	"\x16GetStakeholderResponse\x12:\n" +
	"\vstakeholder\x18\x01 \x01(\v2\x18.stakeholder.StakeholderR\vstakeholder\"\x1b\n" +
	"\x19GetAllStakeholdersRequest\"Z\n" +
	"\x1aGetAllStakeholdersResponse\x12<\n" +
	"\fstakeholders\x18\x01 \x03(\v2\x18.stakeholder.StakeholderR\fstakeholders2\xba\x02\n" +
	"\x12StakeholderService\x12b\n" +
	"\x11CreateStakeholder\x12%.stakeholder.CreateStakeholderRequest\x1a&.stakeholder.CreateStakeholderResponse\x12Y\n" +
	"\x0eGetStakeholder\x12\".stakeholder.GetStakeholderRequest\x1a#.stakeholder.GetStakeholderResponse\x12e\n" +
	"\x12GetAllStakeholders\x12&.stakeholder.GetAllStakeholdersRequest\x1a'.stakeholder.GetAllStakeholdersResponseB\tZ\a./protob\x06proto3"

var (
	file_proto_stakeholder_service_proto_rawDescOnce sync.Once
	file_proto_stakeholder_service_proto_rawDescData []byte
)

func file_proto_stakeholder_service_proto_rawDescGZIP() []byte {
	file_proto_stakeholder_service_proto_rawDescOnce.Do(func() {
		file_proto_stakeholder_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_stakeholder_service_proto_rawDesc), len(file_proto_stakeholder_service_proto_rawDesc)))
	})
	return file_proto_stakeholder_service_proto_rawDescData
}

var file_proto_stakeholder_service_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_stakeholder_service_proto_goTypes = []any{
	(*Stakeholder)(nil),                // 0: stakeholder.Stakeholder
	(*CreateStakeholderRequest)(nil),   // 1: stakeholder.CreateStakeholderRequest
	(*CreateStakeholderResponse)(nil),  // 2: stakeholder.CreateStakeholderResponse
	(*GetStakeholderRequest)(nil),      // 3: stakeholder.GetStakeholderRequest
	(*GetStakeholderResponse)(nil),     // 4: stakeholder.GetStakeholderResponse
	(*GetAllStakeholdersRequest)(nil),  // 5: stakeholder.GetAllStakeholdersRequest
	(*GetAllStakeholdersResponse)(nil), // 6: stakeholder.GetAllStakeholdersResponse
}
var file_proto_stakeholder_service_proto_depIdxs = []int32{
	0, // 0: stakeholder.CreateStakeholderRequest.stakeholder:type_name -> stakeholder.Stakeholder
	0, // 1: stakeholder.CreateStakeholderResponse.stakeholder:type_name -> stakeholder.Stakeholder
	0, // 2: stakeholder.GetStakeholderResponse.stakeholder:type_name -> stakeholder.Stakeholder
	0, // 3: stakeholder.GetAllStakeholdersResponse.stakeholders:type_name -> stakeholder.Stakeholder
	1, // 4: stakeholder.StakeholderService.CreateStakeholder:input_type -> stakeholder.CreateStakeholderRequest
	3, // 5: stakeholder.StakeholderService.GetStakeholder:input_type -> stakeholder.GetStakeholderRequest
	5, // 6: stakeholder.StakeholderService.GetAllStakeholders:input_type -> stakeholder.GetAllStakeholdersRequest
	2, // 7: stakeholder.StakeholderService.CreateStakeholder:output_type -> stakeholder.CreateStakeholderResponse
	4, // 8: stakeholder.StakeholderService.GetStakeholder:output_type -> stakeholder.GetStakeholderResponse
	6, // 9: stakeholder.StakeholderService.GetAllStakeholders:output_type -> stakeholder.GetAllStakeholdersResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_stakeholder_service_proto_init() }
func file_proto_stakeholder_service_proto_init() {
	if File_proto_stakeholder_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_stakeholder_service_proto_rawDesc), len(file_proto_stakeholder_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_stakeholder_service_proto_goTypes,
		DependencyIndexes: file_proto_stakeholder_service_proto_depIdxs,
		MessageInfos:      file_proto_stakeholder_service_proto_msgTypes,
	}.Build()
	File_proto_stakeholder_service_proto = out.File
	file_proto_stakeholder_service_proto_goTypes = nil
	file_proto_stakeholder_service_proto_depIdxs = nil
}
