// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: proto/stakeholder_service.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StakeholderService_CreateStakeholder_FullMethodName  = "/stakeholder.StakeholderService/CreateStakeholder"
	StakeholderService_GetStakeholder_FullMethodName     = "/stakeholder.StakeholderService/GetStakeholder"
	StakeholderService_GetAllStakeholders_FullMethodName = "/stakeholder.StakeholderService/GetAllStakeholders"
)

// StakeholderServiceClient is the client API for StakeholderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Definisanje gRPC servisa
type StakeholderServiceClient interface {
	CreateStakeholder(ctx context.Context, in *CreateStakeholderRequest, opts ...grpc.CallOption) (*CreateStakeholderResponse, error)
	GetStakeholder(ctx context.Context, in *GetStakeholderRequest, opts ...grpc.CallOption) (*GetStakeholderResponse, error)
	GetAllStakeholders(ctx context.Context, in *GetAllStakeholdersRequest, opts ...grpc.CallOption) (*GetAllStakeholdersResponse, error)
}

type stakeholderServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStakeholderServiceClient(cc grpc.ClientConnInterface) StakeholderServiceClient {
	return &stakeholderServiceClient{cc}
}

func (c *stakeholderServiceClient) CreateStakeholder(ctx context.Context, in *CreateStakeholderRequest, opts ...grpc.CallOption) (*CreateStakeholderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateStakeholderResponse)
	err := c.cc.Invoke(ctx, StakeholderService_CreateStakeholder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stakeholderServiceClient) GetStakeholder(ctx context.Context, in *GetStakeholderRequest, opts ...grpc.CallOption) (*GetStakeholderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStakeholderResponse)
	err := c.cc.Invoke(ctx, StakeholderService_GetStakeholder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stakeholderServiceClient) GetAllStakeholders(ctx context.Context, in *GetAllStakeholdersRequest, opts ...grpc.CallOption) (*GetAllStakeholdersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllStakeholdersResponse)
	err := c.cc.Invoke(ctx, StakeholderService_GetAllStakeholders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StakeholderServiceServer is the server API for StakeholderService service.
// All implementations must embed UnimplementedStakeholderServiceServer
// for forward compatibility.
//
// Definisanje gRPC servisa
type StakeholderServiceServer interface {
	CreateStakeholder(context.Context, *CreateStakeholderRequest) (*CreateStakeholderResponse, error)
	GetStakeholder(context.Context, *GetStakeholderRequest) (*GetStakeholderResponse, error)
	GetAllStakeholders(context.Context, *GetAllStakeholdersRequest) (*GetAllStakeholdersResponse, error)
	mustEmbedUnimplementedStakeholderServiceServer()
}

// UnimplementedStakeholderServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStakeholderServiceServer struct{}

func (UnimplementedStakeholderServiceServer) CreateStakeholder(context.Context, *CreateStakeholderRequest) (*CreateStakeholderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateStakeholder not implemented")
}
func (UnimplementedStakeholderServiceServer) GetStakeholder(context.Context, *GetStakeholderRequest) (*GetStakeholderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStakeholder not implemented")
}
func (UnimplementedStakeholderServiceServer) GetAllStakeholders(context.Context, *GetAllStakeholdersRequest) (*GetAllStakeholdersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllStakeholders not implemented")
}
func (UnimplementedStakeholderServiceServer) mustEmbedUnimplementedStakeholderServiceServer() {}
func (UnimplementedStakeholderServiceServer) testEmbeddedByValue()                            {}

// UnsafeStakeholderServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StakeholderServiceServer will
// result in compilation errors.
type UnsafeStakeholderServiceServer interface {
	mustEmbedUnimplementedStakeholderServiceServer()
}

func RegisterStakeholderServiceServer(s grpc.ServiceRegistrar, srv StakeholderServiceServer) {
	// If the following call pancis, it indicates UnimplementedStakeholderServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StakeholderService_ServiceDesc, srv)
}

func _StakeholderService_CreateStakeholder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateStakeholderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StakeholderServiceServer).CreateStakeholder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StakeholderService_CreateStakeholder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StakeholderServiceServer).CreateStakeholder(ctx, req.(*CreateStakeholderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StakeholderService_GetStakeholder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStakeholderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StakeholderServiceServer).GetStakeholder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StakeholderService_GetStakeholder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StakeholderServiceServer).GetStakeholder(ctx, req.(*GetStakeholderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StakeholderService_GetAllStakeholders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllStakeholdersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StakeholderServiceServer).GetAllStakeholders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StakeholderService_GetAllStakeholders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StakeholderServiceServer).GetAllStakeholders(ctx, req.(*GetAllStakeholdersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StakeholderService_ServiceDesc is the grpc.ServiceDesc for StakeholderService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StakeholderService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "stakeholder.StakeholderService",
	HandlerType: (*StakeholderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateStakeholder",
			Handler:    _StakeholderService_CreateStakeholder_Handler,
		},
		{
			MethodName: "GetStakeholder",
			Handler:    _StakeholderService_GetStakeholder_Handler,
		},
		{
			MethodName: "GetAllStakeholders",
			Handler:    _StakeholderService_GetAllStakeholders_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/stakeholder_service.proto",
}
