FROM golang:latest AS builder

WORKDIR /app

# Copy both directories
COPY Stakeholders/ ./Stakeholders/
COPY Tours/ ./Tours/

WORKDIR /app/Tours

RUN go mod tidy

RUN CGO_ENABLED=0 GOOS=linux go build -o /tour-service ./cmd/main.go

FROM alpine:latest

COPY --from=builder /tour-service /tour-service
COPY --from=builder /app/Tours/.env ./.env
EXPOSE 8083

CMD ["/tour-service"]